### ISSUE TITLE
MC subshell not available for non-root users for debian-stretch

### ISSUE THREAD

**Issue by kenashkov** [debuerreotype/docker-debian-artifacts#105]
Hi,
I have been trying for few days to solve the problem in debian-stretch that the MC subshell is not available for the non root users.
I test it with USER in the docker file or by starting the vanilla debian stretch image and then doing
```
# useradd -m test1
```
Then in another host shell:
```
$ docker exec -it -u test1 container_image /bin/bash
```
And then executing $ mc
In both cases the subshell is not available (for root is fine).

I just tested debian buster I noted there is no such issue. So I will just port my containers to debian buster but I decided to report the issue in case someone know what the reason could be. (I also tested debian stretch in VM and the MC subshell works fine).

**Comment by tianon** [comment]
I'm not sure what you're referring to?  Our published images are (intentionally) very minimal, so the non-essential `mc` package is not included (especially since it's trivial to install):

```dockerfile
FROM debian:stretch
RUN apt-get update && apt-get install -y mc
```

During that build:

```
After this operation, 109 MB of additional disk space will be used.
```

(That's larger than our whole current image!)

**Comment by kenashkov** [comment]
Hi,
Yes, mc needs to be installed separately, this is not what Im referring to, but a specific functionality of mc. mc subshell is when you execute a command and try to see the output with ctrl+o in mc (you can check is it compiled/supported with `mc -V` - it shows "With subshell support as default"). If subshell is enabled the command will be executed (and you can see the output with ctrl+o and if needed to execute additional commands while mc is hidden). The problem is not a lacking library (as the subshell is compiled and works for root) but some setting that prevents this behavior for non-root users.

I just tried with:
```
$ docker exec -it -u test1 container_image /usr/bin/mc
```
And the subshell is not working.

And my point was that this works on Buster without any additional changes (and it also works in Stretch in VM). So it appears to be something specific for the Stretch docker image...

Indeed installing mc adds 100+ MB to the image but Im using this for dev purpose so the size is not an issue (in fact there are many other tools installed too).

**Comment by yosifkit** [comment]
From some initial testing, you likely need to set the login shell of the user when it is created. I also had to make sure the user had a writable home directory (`--create-home`).

```console
Usage: useradd [options] LOGIN
...
  -s, --shell SHELL             login shell of the new account
...
$ useradd --create-home --shell /bin/bash test1
```
