### ISSUE TITLE
Can't install postgresql in stretch-slim

### ISSUE THREAD

**Issue by eigood** [debuerreotype/docker-debian-artifacts#11]
```
Setting up postgresql-client-9.6 (9.6.3-3) ...
update-alternatives: using /usr/share/postgresql/9.6/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/psql.1.gz.dpkg-tmp': No such file or directory
```

So, you can remove the files from the man folders, but don't remove the directories.  I don't think u-a should create the missing intervening directories in this case.

**Comment by tianon** [comment]
Indeed, see https://github.com/debuerreotype/debuerreotype/issues/10 for where this has been more actively discussed.

**Comment by eigood** [comment]
Close this ticket then, as the other was created first, and has more history.
