### ISSUE TITLE
Potential Malware Detected

### ISSUE THREAD

**Issue by davidlday** [debuerreotype/docker-debian-artifacts#110]
The commercial image scanner I use is reporting malware found in debian:buster and debian:buster-slim on amd64. So far I haven't found any public information what it's reporting. I also don't see any special channels for reporting potential security information. What's the best way of sharing the information I have?

**Comment by tianon** [comment]
Feel free to share it via email directly with me, if that's comfortable for you - tianon@debian.org.

I'm dubious, but willing to take a look! :+1:

**Comment by davidlday** [comment]
Thank you much. Email sent.

**Comment by elja** [comment]
I think we're seeing the same issue in our commercial image scanner

**Comment by nerocom** [comment]
+1

**Comment by tianon** [comment]
I've confirmed that both cases that have been sent to me are the same report -- they're both following up with the scanning vendor (and I encourage anyone seeing a similar report to do the same), who will hopefully confirm quickly whether they believe this is real or their system being a little too aggressive.

**Comment by davidlday** [comment]
I have informal communication that this was a false positive from our scanner. I consider my issue resolved but will leave the issue open since others have reported similar. Thanks, @tianon!

**Comment by hrmtacos** [comment]
Same, our scan vendor says it's false positive. Looks like we're good

**Comment by tianon** [comment]
Excellent, thanks folks! :+1:
