### ISSUE TITLE
ECR Scan Issue 

### ISSUE THREAD

**Issue by gita-v** [debuerreotype/docker-debian-artifacts#118]
Hi 😄 
Looks like the new `buster-slim` base image has some issue with Amazon ECR -- 
The new release does not pass Amazon's image scan status -- I receive the error `UnsupportedImageError: The operating system and/or package manager are not supported.`
I have to go back to `debian:buster-20210111-slim` for the scan to be resolved. Do you know what has changed with this rebuild? 

According to amazon, an image scan can fail
`when attempting to scan an image that was built using an operating system that Amazon ECR doesn't support image scanning for`

Has the build pipeline changed for the new image?

**Comment by tianon** [comment]
This sounds like there's probably a bug in ECR's OS detection -- nothing substantive has changed in the image?

```console
$ docker pull debian:buster-slim
buster-slim: Pulling from library/debian
Digest: sha256:13f0764262a064b2dd9f8a828bbaab29bdb1a1a0ac6adc8610a0a5f37e514955
Status: Image is up to date for debian:buster-slim
docker.io/library/debian:buster-slim

$ docker run --rm debian:buster-slim cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ docker run --rm debian:buster-slim dpkg --version
Debian 'dpkg' package management program version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
$ docker run --rm debian:buster-slim apt-get --version
apt 1.8.2.2 (amd64)
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 Pkg:  Debian APT planner interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
 Idx: EIPP scenario file
$ docker run --rm debian:buster-slim cat /etc/debian_version
10.8
```

(Certainly not anything that would make it "hard" to detect as Debian... :grimacing:)

**Comment by gita-v** [comment]
Thanks for getting back to me so fast 
🤔  Any substantial change between the  `debian:buster-20210111-slim` and the latest?

**Comment by gita-v** [comment]
You're right --- it is an issue on Amazon's side 🤦
