### ISSUE TITLE
bullseye: apt not working

### ISSUE THREAD

**Issue by mnacharov** [debuerreotype/docker-debian-artifacts#122]
```
pi@store:~$ docker pull arm32v7/debian:bullseye-slim
bullseye-slim: Pulling from arm32v7/debian
e5398822d76b: Already exists 
Digest: sha256:d6ee6ca6672f5ec285bbf4f3e1a88696624ac14af6479e57fa6feddaec8c09ba
Status: Downloaded newer image for arm32v7/debian:bullseye-slim
docker.io/arm32v7/debian:bullseye-slim
pi@store:~$ docker run -it --rm arm32v7/debian:bullseye-slim
root@eebb868f17ab:/# apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [142 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [40.1 kB]
Err:2 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by mnacharov** [comment]
Looks like it's docker issue
https://stackoverflow.com/a/64843925/3282927
```
pi@store:~$ docker run -it --rm arm32v7/debian:buster-slim /bin/date
Fri Mar 12 13:25:48 UTC 2021
pi@store:~$ docker run -it --rm arm32v7/debian:bullseye-slim /bin/date
Thu Jan  1 00:00:00 UTC 1970
```

**Comment by mnacharov** [comment]
same issue affected to alpine 3.13
```
pi@store:~$ docker run -it --rm arm32v7/alpine:3.12.4 /bin/date
Fri Mar 12 13:39:31 UTC 2021
pi@store:~$ docker run -it --rm arm32v7/alpine:3.13.2 /bin/date
Sun Jan  0 00:100:4174038  1900
```

**Comment by mnacharov** [comment]
looks related to linux kernel v4 v5 difference

**Comment by stappersg** [comment]
On Fri, Mar 12, 2021 at 05:44:52AM -0800, Mikhail Nacharov wrote:
> looks related to linux kernel v4 v5 difference

That observation plus my knowledge:

  Recent docker images need recent counter parts

**Comment by tianon** [comment]
This is the same as #106, #97 (for a couple other semi-recent examples).  TLDR, you'll need to update your host, specifically to:

- Docker version 19.03.9 or newer
- libseccomp version 2.4.2 or newer

See https://github.com/moby/moby/issues/40734 for more details around this (and similar issues).

**Comment by icsy7867** [comment]
I'm having this exact issue.  Buster works fine.  Bullseye is having this problem.  Plenty of free space.  Also tried clearing apt cache as well.

**Comment by tianon** [comment]
> This is the same as #106, #97 (for a couple other semi-recent examples). TLDR, you'll need to update your host, specifically to:
> 
> * Docker version 19.03.9 or newer
> * libseccomp version 2.4.2 or newer
> 
> See [moby/moby#40734](https://github.com/moby/moby/issues/40734) for more details around this (and similar issues).

You might need to go as high as Docker 20.10.10+ depending on which version of the issue you're running into.

**Comment by icsy7867** [comment]
> > This is the same as #106, #97 (for a couple other semi-recent examples). TLDR, you'll need to update your host, specifically to:
> > 
> > * Docker version 19.03.9 or newer
> > * libseccomp version 2.4.2 or newer
> > 
> > See [moby/moby#40734](https://github.com/moby/moby/issues/40734) for more details around this (and similar issues).
> 
> You might need to go as high as Docker 20.10.10+ depending on which version of the issue you're running into.

I'm running 20.10.12 on Buster arm.

Also I noticed that
docker run -it debian:bullseye date returns

January 1 00:00:00 1970

However on Buster I get the correct date.

**Comment by tianon** [comment]
You need newer libseccomp too.

**Comment by icsy7867** [comment]
I was able to bandaid this on Buster.

`
sudo vi /etc/apt/sources.list
### Add the backports repo
deb http://deb.debian.org/debian buster-backports main

### Add GPG Keys
gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg --export 04EE7237B7D453EC | sudo apt-key add -
gpg --export 648ACFD622F3D138 | sudo apt-key add -

### Install libseccomp from backports:
sudo apt install -t buster-backports libseccomp-dev
`

**Comment by ChengLiPP** [comment]
fixed mine with a simple
```
docker system prune
```
Check here https://stackoverflow.com/a/65524014, hope it helps anyone
