### ISSUE TITLE
Transparency on when docker images are updated

### ISSUE THREAD

**Issue by macrotex** [debuerreotype/docker-debian-artifacts#133]
It would be helpful if the team that generates the Debian docker images provided some information on when the images are updated in DockerHub. For example, are new images generated on certain security fixes being available? Or are new images generated based on enough time passing? If so, how much time? 

Whatever the trigger is, it would help in planning if this information were made public.

**Comment by tianon** [comment]
That's a great idea -- it's referenced in https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves, but it would be much better for us to update this repository with that information and then have that FAQ point back here instead.

The long and short of it is that we try to rebuild at least every 30 days or so, earlier if there's a release or a severe security issue that warrants rebuilding sooner -- the reason we try not to rebuild more often than 30 days is that the downstream rebuild effect every time we update is _immense_. :grimacing:

As I've noted in #134, there's a rebuild currently in progress for Saturday's release of Bullseye, which is just a tad shorter than our normal cadence (it's been about 25 days, not quite 30).
