### ISSUE TITLE
Debian latest docker

### ISSUE THREAD

**Issue by peterd550** [debuerreotype/docker-debian-artifacts#139]
When I am using Debian latest and I
RUN apt-get -y update
I get this error message

The command '/bin/bash -c apt-get update' returned a non-zero code: 100

Works fine with Debian:10.10

**Comment by tianon** [comment]
Sounds a lot like https://github.com/debuerreotype/docker-debian-artifacts/issues/122, but I'm afraid without more output there's nothing much we can do to help debug further.

I bet if you update your Docker, runc, and/or libseccomp, the problem will no longer exhibit.
