### ISSUE TITLE
Locale definition of doc not working on stretch-slim

### ISSUE THREAD

**Issue by joserprieto** [debuerreotype/docker-debian-artifacts#14]
The line on the README:

```
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
```

Didn't work on stretch-slim.

This works for me:

```
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /etc/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
```

**Comment by tianon** [comment]
Correct -- the `slim` image variants exclude all docs _and_ locales, so I believe this is working-as-designed.

See [debuerreotype's `.slimify-excludes` file](https://github.com/debuerreotype/debuerreotype/blob/76e05575e9bbb3bdec52fc3f56820828c425cea9/scripts/.slimify-excludes) for a full list of what's currently excluded at the `dpkg` level for the `slim` image variants.

Another solution would be to modify the `dpkg` configuration in your `slim`-based image to comment out or remove the line which excludes `/usr/share/locale`.
