### ISSUE TITLE
please add sudo

### ISSUE THREAD

**Issue by tjaalton** [debuerreotype/docker-debian-artifacts#142]
Guess I'm just trying my luck here, but would it be possible to include sudo in the 'fat' image? Azure pipelines require it in order to install packages to the image..

**Comment by tianon** [comment]
These images are (as of Bullseye) a faithful `debootstrap --variant=minbase`.  Given the nature of container layering, things like `sudo` are pretty easy to add, but are impossible to actually remove if they're added at a lower level.

If Azure doesn't give you a means by which to build a custom image including `sudo` directly in your pipeline, I would suggest creating/maintaining one with something even as simple as the following, which should be reasonably easy to keep up to date:

```dockerfile
FROM debian:bullseye
RUN apt-get update && apt-get install -y sudo
```

**Comment by tjaalton** [comment]
and that's what I've done, but it's pretty silly to have to do that

Fedora has sudo on their images, but oh well
