### ISSUE TITLE
stable and testing riscv64 support?

### ISSUE THREAD

**Issue by mcandre** [debuerreotype/docker-debian-artifacts#157]
The advertised architecture riscv64 appears to be missing an image for the bullseye and bookworm editions of Debian.

As a workaround, I suppose I can target unstable sid. But I'd really like to use riscv64 as a stable or testing release.

**Comment by tianon** [comment]
Unfortunately, Debian does not include `riscv64` as a "release architecture" -- it's part of the "Debian Ports" project.  As such, it's unfortunately only supported for `sid` (`unstable`) and `experimental`.

See also:

- https://ports.debian.org/
- https://ftp-master.debian.org/archive-criteria.html
- https://dsa.debian.org/ports/hardware-requirements/
- https://release.debian.org/testing/arch_policy.html
- https://wiki.debian.org/PortsDocs/New

Once `riscv64` is a release architecture, it will include builds of `testing` (and eventually `stable`).

**Comment by mcandre** [comment]
Understood.

I may pin my Dockerfiles to a timestamped sid tag or a hash for now.

**Comment by tuler** [comment]
riscv64 is [officially supported](https://lists.debian.org/debian-riscv/2023/07/msg00053.html) since July 2023. What is the blocker for having it in stable? Can this issue be reopened @tianon ?

**Comment by yosifkit** [comment]
When https://deb.debian.org/debian/dists/stable/main/binary-riscv64/ exists, it can be added as a stable architecture. There are currently `riscv64` images for `unstable` (`sid`), and `testing` (aka the next stable release, `trixie`), so there will likely be `riscv64` images for `stable` when `trixie` is released as stable later this year.

There will never be `riscv64` images for `bullseye` or `bookworm` as it was not supported for those releases.
