### ISSUE TITLE
Outstanding CVEs in buster and buster slim images

### ISSUE THREAD

**Issue by priyankajayaswal1** [debuerreotype/docker-debian-artifacts#158]
Debian released a openssl security update patching some of the issues, as per https://lists.debian.org/debian-security-announce/2022/msg00071.html

Can we get those updates in for the docker images as well? https://hub.docker.com/_/debian/?tab=tags&page=1&ordering=last_updated&name=buster

Thanks!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/12133 :+1:
