### ISSUE TITLE
debian:latest apt update: The repository 'http://deb.debian.org/debian-security bullseye-security Release' does not have a Release file.

### ISSUE THREAD

**Issue by casdevs** [debuerreotype/docker-debian-artifacts#166]
Since debian:11.4 has been released,
when running
```docker run --rm -it debian:11.4 apt update```
we get the error
```The repository 'http://deb.debian.org/debian-security bullseye-security Release' does not have a Release file.```

Is the apt sources list in the image up-to-date?

Maybe it has something to do with
https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#security-archive ?

The ```latest``` and ```-slim``` images also seem to be affected.

Thanks in advance!

**Comment by tianon** [comment]
I can't reproduce -- does your environment have a firewall or proxy of some kind that might be interfering?

**Comment by casdevs** [comment]
Thanks @tianon  for the hint!

We've CNAME'd ```deb.debian.org``` to a local mirror that returns 404 errors for ```debian-security``` since 11.4.
Removing the CNAME solved the problem.
