### ISSUE TITLE
Update docker hub docs for latest stable version of the debian image

### ISSUE THREAD

**Issue by oriordanniall** [debuerreotype/docker-debian-artifacts#167]
According to [docker hub docs](https://hub.docker.com/_/debian#:~:text=The%20debian%3Alatest%20tag%20will%20always%20point%20the%20latest%20stable%20release%20(which%20is%2C%20at%20the%20time%20of%20this%20writing%2C%20debian%3Abuster)) the latest version of the debian image is `buster`. However, the [official release notes for debian](https://www.debian.org/releases/#:~:text=The%20current%20stable%20distribution%20of,released%20on%20July%209th%2C%202022.) specify that `bullseye` is the current stable version for the debian image and buster is  an oldstable release.

Please let me know if there is a more appropriate place to raise this issue

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/docs/pull/2180 :+1:
