### ISSUE TITLE
base image update needed

### ISSUE THREAD

**Issue by mythi** [debuerreotype/docker-debian-artifacts#168]
We have a multi-staged build using `debian:unable-slim` like this:

```
FROM debian:unstable-slim AS builder
RUN apt update && apt install -y --no-install-recommends <build deps> && <build & install>
...
FROM debian:unstable-slim
COPY --from=builder <...>
...
```

currently, the base image and unstable (and testing) repos give different glibc versions so we get broken binaries in the final image:

```
foo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by foo)
```

can we get the base images updated?

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/13005 :+1:

**Comment by mythi** [comment]
@tianon thanks!

**Comment by mythi** [comment]
FYI, looks like this triggers again w/  2.37 -> 2.38.
