### ISSUE TITLE
buster-20220822 dropped some arch support

### ISSUE THREAD

**Issue by siggy** [debuerreotype/docker-debian-artifacts#170]
`debian:buster-20220822-slim` and friends dropped support for a number of architectures: 

```bash
$ docker manifest inspect debian:buster-20220801-slim | jq -r '.manifests[].platform | "\(.architecture)/\(.os)/\(.variant)"'
amd64/linux/null
arm/linux/v5
arm/linux/v7
arm64/linux/v8
386/linux/null
mips64le/linux/null
ppc64le/linux/null
s390x/linux/null

$ docker manifest inspect debian:buster-20220822-slim | jq -r '.manifests[].platform | "\(.architecture)/\(.os)/\(.variant)"'
amd64/linux/null
arm/linux/v7
arm64/linux/v8
386/linux/null
```

is this expected? i haven't been able to identify the root cause of this. here are some places that appear to be related:

- buster with `arm32v5`: https://github.com/debuerreotype/docker-debian-artifacts/tree/155640b6e2e249dfaeee8795d5de539ef3e49417
- `buster` now missing from `dist-arm32v5`: https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-arm32v5
- docker.debian.net: https://github.com/debuerreotype/debuerreotype.github.io/commit/90a126660be7f7db381a647d22a32214b7b02d93#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5R58-R65

**Comment by tianon** [comment]
Yes, this is unfortunately expected -- see https://wiki.debian.org/LTS.

**Comment by tianon** [comment]
See also http://deb.debian.org/debian-security/dists/buster/updates/main/ (the security mirror is now limited to only the set of LTS-supported architectures).

**Comment by siggy** [comment]
Thanks for the helpful info @tianon. I'm going to close this for now (and upgrade our builds to use bullseye).
