### ISSUE TITLE
please make sure usr-is-merged is installed for bookworm, sid

### ISSUE THREAD

**Issue by aburch** [debuerreotype/docker-debian-artifacts#174]
Hi,

we will soon upload a version of init-system-helpers depending on "usrmerge | usr-is-merged" to unstable to start the transition to usrmerge.
Please make sure that usr-is-merged is present in Docker images for Debian bookworm and sid to avoid pulling in extra dependencies via usrmerge.

Recent versions of debootstrap will install the package by default (debootstrap 1.0.127 from testing/unstable; debootstrap 1.0.114+deb10u1, debootstrap 1.0.123+deb11u1 which were part of today's point releases).

Ansgar

**Comment by tianon** [comment]
Thanks for the reminder/poke!  I went and rebuilt all of https://github.com/docker-library/official-images/pull/13132 just to make absolutely sure this was included across all architectures, and it now is:

- https://github.com/debuerreotype/docker-debian-artifacts/blob/8b767b40652eff693130e3364e8636e1e1cd1e53/unstable/rootfs.manifest#L84
- https://github.com/debuerreotype/docker-debian-artifacts/blob/8b767b40652eff693130e3364e8636e1e1cd1e53/bookworm/rootfs.manifest#L86

(For a couple examples.)

:+1:
