### ISSUE TITLE
bullseye-slim seems to be in a broken state

### ISSUE THREAD

**Issue by tastytea** [debuerreotype/docker-debian-artifacts#184]
I'm getting `E: Unable to correct problems, you have held broken packages.` when trying to install new packages with bullseye-slim:latest a.k.a. bullseye-20221024-slim. It works fine with bullseye-20221004-slim.

[full log](https://codeberg.drone.tzend.de/tastytea/mxstickertool/23/1/2)

**Comment by tianon** [comment]
I can't seem to reproduce a problem :see_no_evil:

I'd suggest removing `-q` and `-qq` from your commands, which should hopefully give you more helpful output for what's failing.

**Comment by tastytea** [comment]
Oh yeah, my package priority configuration was broken. Sorry. :sweat_smile:
