### ISSUE TITLE
Cannot run "apt update" in bookworm or bookworm-slim.

### ISSUE THREAD

**Issue by jmssil** [debuerreotype/docker-debian-artifacts#187]
root@f2d417c5fef9:/# apt update
Get:1 http://deb.debian.org/debian bookworm InRelease [164 kB]
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [49.6 kB]
Err:1 http://deb.debian.org/debian bookworm InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian-security bookworm-security InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bookworm-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code

**Comment by jmssil** [comment]
Yes, I just tried in a Debian 12 host (docker 20.10.21) and it worked. I was previously running in Debian 10 (docker 18.09.1).

**Comment by tianon** [comment]
Glad you got it sorted!
