### ISSUE TITLE
Issue using sudo with latest Docker release (4.16)

### ISSUE THREAD

**Issue by Dnd-Mafer** [debuerreotype/docker-debian-artifacts#188]
Hello,

We are using our custom images based on the debian ones for a while. Since [Docker Desktop 4.16](https://docs.docker.com/desktop/release-notes/#4160) released yesterday, we meet this error
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

Here is the shortest Dockerfile to reproduce the error:
```
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -yq --no-install-recommends sudo
USER www-data
RUN sudo ls -l
```

I'm surprised that nobody struggles with this issue. Am I missing something ?

A few clarifications : 
- we are working on Mac (Apple or Intel chipset lead to the same issue).
- none of our custom images were modified since the last Docker release
- we know that we should avoid using `sudo` in Dockerfile but in our case, we have to :)  
- we tried on buster, same result

Thank you for helping 🙏

**Comment by Dnd-Juver** [comment]
https://github.com/docker/for-mac/issues/6675

**Comment by tianon** [comment]
Nice find! This does look like it's a Docker Desktop bug, so I'm going to go ahead and close this; hopefully they get it fixed quickly!
