### ISSUE TITLE
Clean install packages apt wrapper

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [debuerreotype/docker-debian-artifacts#189]
Hello!

I was thinking because in every tutorial for Debian-based Docker images is a part about removing apt sources list, cache etc.

So what about writing some thin wrapper for apt (`dockapt`? ;D) which will do a few things:
- update apt lists
- install mentioned packages with --yes option
- remove the apt lists, caches right after installation

I saw a few similar scripts in some repositories in the past, and it was a little awkward to rewrite/copy these but still, I find them quite useful (cleaner Dockerfile, easier for newbies)

What do you think?

Best regards

**Comment by tianon** [comment]
I've thought about doing so before, but I really want to avoid writing too many things that deviate from a standard Debian install/`debootstrap`, especially things that are so explicitly user-facing differences.  Users choosing to do so in their own images is very different from me actively encouraging them in such an official capacity. :sweat_smile:

(I already get a fair amount of heat periodically from other project members who disagree with a lot of the things that are or aren't included as it is :grimacing:)

**Comment by tomaszkrzyzanowski** [comment]
I see ;)

> (I already get a fair amount of heat periodically from other project members who disagree with a lot of the things that are or aren't included as it is :grimacing:)
I can only imagine :) 

and in some way it's understandable - trying to be as similar to upstream as possible.

It was a difficult time for me to use ie. official PHP Docker image because of the quirks/customized things there - Debian + Ondrej's was looking back then like more sensible/familiar solution

Anyway, thank you for response
