### ISSUE TITLE
Build Debian 9 with latest kernel 4.9.65-3

### ISSUE THREAD

**Issue by frekele** [debuerreotype/docker-debian-artifacts#19]
Build Debian 9 with latest kernel 4.9.65-3.

### Debian 4.9.65-3 (2017-12-03) x86_64

**Comment by tianon** [comment]
Uhh, I'm not sure you've filed this in the appropriate place -- this is for the Debian Docker base images, which don't ever include a kernel (since containers by their nature share the host's kernel directly).

**Comment by frekele** [comment]
ok.

**Comment by frekele** [comment]
I'm going to close this issue.

**Comment by tianon** [comment]
Ah, that was updated in https://github.com/docker-library/official-images/pull/3791, and the official image build servers are still churning through updates (but the base updates should be up). :+1:
