### ISSUE TITLE
debian:12 docker image is not yet available

### ISSUE THREAD

**Issue by v1v** [debuerreotype/docker-debian-artifacts#196]
debian:12 docker image is not yet available, I don't know whether this is the right place to notify that. I can see https://github.com/debuerreotype/docker-debian-artifacts/blob/4648ad5c6feb1318b8a6c31502ebde8bb18ebb5e/bookworm/Dockerfile which points to the tags `[bookworm, bookworm-20230522]`

Thanks

**Comment by v1v** [comment]
Thanks for your prompt answer 🙏

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/14832
