### ISSUE TITLE
Problem executing scripts APT::Update::Post-Invoke

### ISSUE THREAD

**Issue by V-Smeets** [debuerreotype/docker-debian-artifacts#197]
Building the Dockerfile
> FROM debian:stable AS build
> RUN apt-get update

results in the error:

> $ docker build .
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM debian:stable AS build
>  ---> 2069fecd422e
> Step 2/2 : RUN apt-get update
>  ---> Running in 385a90a81455
> Get:1 http://deb.debian.org/debian stable InRelease [147 kB]
> Get:2 http://deb.debian.org/debian stable-updates InRelease [52.1 kB]
> Get:3 http://deb.debian.org/debian-security stable-security InRelease [48.0 kB]
> Get:4 http://deb.debian.org/debian stable/main amd64 Packages [8904 kB]
> Get:5 http://deb.debian.org/debian-security stable-security/main amd64 Packages [17.6 kB]
> Fetched 9169 kB in 3s (2895 kB/s)
> Reading package lists...
> E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
> E: Sub-process returned an error code
> The command '/bin/sh -c apt-get update' returned a non-zero code: 100
> $

**Comment by yosifkit** [comment]
This seems to exhibit in a way similar to https://github.com/debuerreotype/docker-debian-artifacts/issues/122 and related issues. Try updating libseccomp and Docker on the host (https://github.com/debuerreotype/docker-debian-artifacts/issues/122#issuecomment-805304431).

**Comment by V-Smeets** [comment]
Thank you,
that will be the problem because the used docker version (20.10) is rather old.

**Comment by devaroop** [comment]
Upon updating docker to latest version this started working for me. Thank you

**Comment by silverkorn** [comment]
Hmm... `20.10.24` is 2 only months old: https://docs.docker.com/engine/release-notes/20.10/
