### ISSUE TITLE
stable-backports: warning raised

### ISSUE THREAD

**Issue by osallou** [debuerreotype/docker-debian-artifacts#2]
When updating package list (apt-get update), a warning is raised:

W: Conflicting distribution: http://deb.debian.org/debian stable-backports InRelease (expected stable-backports but got stretch-backports)

**Comment by tianon** [comment]
Indeed, this is expected given the following:
```console
$ curl -fsSL 'http://deb.debian.org/debian/dists/stable-backports/Release' | grep -E '^Suite|^Codename'
Suite: stretch-backports
Codename: stretch-backports
```

(Compare to:)

```console
$ curl -fsSL 'http://deb.debian.org/debian/dists/stable/Release' | grep -E '^Suite|^Codename'
Suite: stable
Codename: stretch
```

The warning is harmless and should not affect usage (it simply reflects a labelling choice of the Debian FTP team). :+1:
