### ISSUE TITLE
Missing `procps` package or feature? (>=debian:stretch)

### ISSUE THREAD

**Issue by TxGVNN** [debuerreotype/docker-debian-artifacts#20]
I see `procps` no longer from `debian:stretch`.
I wonder we are missed or this is a feature?

Regards,

**Comment by tianon** [comment]
Definitely a feature -- it's not part of Debian's "essential" set, and thus is not included in the image.

See also https://github.com/tianon/docker-brew-debian/issues/13, https://github.com/tianon/docker-brew-debian/issues/14, and https://github.com/debuerreotype/docker-debian-artifacts/issues/5 for some previous discussions of this same topic.
