### ISSUE TITLE
Add `latest-slim` tag alias

### ISSUE THREAD

**Issue by Jorropo** [debuerreotype/docker-debian-artifacts#205]
Hey I am maintaining some docker image and I don't personally care about what release of debian I am using, I just want whatever is debian stable at which is provided by the `latest` tag.
However we currently use a `-slim` and I can't specify `latest-slim` AFAIT.

**Comment by tianon** [comment]
Honestly, I'd probably be more likely to go the other direction and get rid of `latest` entirely 😅

I think we have a `stable-slim` alias, though, which should be exactly what you're after 👀

**Comment by Jorropo** [comment]
Oh yes my bad. Thx :heart:

**Comment by Jorropo** [comment]
It is weird because stable is it's own line in https://hub.docker.com/_/debian instead of being an alias of `bookworm-slim`.
I overlooked `stable` because `latest` was the only non versioned alias of `bookworm-slim` while `stable-slim` is so far down the page I have to scroll to see it.

**Comment by tianon** [comment]
Yeah, `stable` is slightly different in that the `sources.list` in it literally points to `stable` instead of a specific codename, but for your use case it should be exactly what you're looking for. 😅

**Comment by Jorropo** [comment]
Make sense, we don't run the images for long, we have a new release of our software which will pick up debian at the time about every month.
I don't think `sources.list` is ever touched on our boxes, but it's fine.

Thx
