### ISSUE TITLE
Docker image ...bookworm ends up with: shell not found

### ISSUE THREAD

**Issue by forgie1** [debuerreotype/docker-debian-artifacts#207]
I'm using Gitlab CI/CD and:

* while image **php:8.2.11-cli-bullseye** is perfectly fine
* iamge **php:8.2.11-bookworm** can not execute commands since **shell not found** error

this is what I can see in pipeline:

```
Executing "step_script" stage of the job script 00:02
Using docker image sha256:31a4051b14f9d8d89f5b23b62ebf7486247e9dea68e3ea32b0be5c6a9729ab78 for php:8.2.11-cli-bookworm with digest php@sha256:9a3f29ea6b20014fbfc27777de38c545c0fc7d657a1bb8bd951851c64b70c14c ...
shell not found
Cleaning up project directory and file based variables 00:03
ERROR: Job failed: exit code 1
```

looks like many people are having this problem:

https://www.reddit.com/r/gitlab/comments/14sf4ve/shell_not_found_in_debian_bookworm_images/
https://forum.gitlab.com/t/jobs-fails-shell-not-found-version-python/88340/10
and more

**Comment by tianon** [comment]
My best guess offhand is libseccomp; I'd suggest making sure Docker, runc, and libseccomp2 on your host are as new/fresh as they can be.

**Comment by forgie1** [comment]
@tianon thank you.

Docker had new version:
apt list libseccomp2
libseccomp2/stable,now 2.5.4-1+b3 amd64 [installed,automatic]

But server with our GitlabRunner had older version:
libseccomp2/oldoldstable,now 2.3.3-4 amd64 [installed]

So I updated Debian on the server with gitlab-runner to latest version 12 bookworm.
And it is working now.
