### ISSUE TITLE
VERSION_ID missing from debian:trixie image (`/etc/os-release`)

### ISSUE THREAD

**Issue by fauust** [debuerreotype/docker-debian-artifacts#209]
Hi!
Is there any particular reason why the `debian:trixie` image does not contain the according `VERSION_ID` in `/etc/os-release` file, see bellow:

```console
.venv ❯ podman run --rm debian:bookworm grep VERSION_ID /etc/os-release
VERSION_ID="12"
.venv ❯ podman run --rm debian:trixie grep VERSION_ID /etc/os-release
```

**Comment by tianon** [comment]
That file is owned by the `base-files` package (https://tracker.debian.org/pkg/base-files):

```console
$ dpkg -S /etc/os-release
base-files: /etc/os-release
```

**Comment by tianon** [comment]
Looking at https://tracker.debian.org/news/1433360/accepted-base-files-13-source-into-unstable/, this was intentional -- if I had to guess, I'd imagine the intent is to signal that "trixie" is not a released version yet.

**Comment by tianon** [comment]
(Closing since there's nothing we are going to change in the image, but feel free to continue discussing here.)

**Comment by fauust** [comment]
Ok, thanks @tianon for the pointers!
