### ISSUE TITLE
Can't install libaio1 anymore

### ISSUE THREAD

**Issue by sienacompany** [debuerreotype/docker-debian-artifacts#217]
#5 22.09 + apt-get install -y libaio1
#5 22.10 Reading package lists...
#5 23.15 Building dependency tree...
#5 23.38 Reading state information...
#5 23.40 Package libaio1 is not available, but is referred to by another package.
#5 23.40 This may mean that the package is missing, has been obsoleted, or
#5 23.40 is only available from another source
#5 23.40 
#5 23.41 E: Package 'libaio1' has no installation candidate

**Comment by sienacompany** [comment]
Last time it worked was April, 23 2024 - early morning

**Comment by tianon** [comment]
I can't reproduce:

```dockerfile
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libaio1
```

```console
$ docker build --pull -
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libaio1

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian:bookworm-slim
bookworm-slim: Pulling from library/debian
b0a0cf830b12: Already exists 
Digest: sha256:155280b00ee0133250f7159b567a07d7cd03b1645714c3a7458b2287b0ca83cb
Status: Downloaded newer image for debian:bookworm-slim
 ---> d5f1e9a5dd4f
Step 2/2 : RUN apt-get update && apt-get install -y libaio1
 ---> Running in 6fc283481493
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [155 kB]
Fetched 9209 kB in 1s (7760 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  libaio1
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.4 kB of archives.
After this operation, 37.9 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libaio1 amd64 0.3.113-4 [13.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 13.4 kB in 0s (1225 kB/s)
Selecting previously unselected package libaio1:amd64.
(Reading database ... 6090 files and directories currently installed.)
Preparing to unpack .../libaio1_0.3.113-4_amd64.deb ...
Unpacking libaio1:amd64 (0.3.113-4) ...
Setting up libaio1:amd64 (0.3.113-4) ...
Processing triggers for libc-bin (2.36-9+deb12u6) ...
Removing intermediate container 6fc283481493
 ---> cccfc02099ec
Successfully built cccfc02099ec
```

**Comment by tianon** [comment]
If I had to guess based on context, I'd guess you're probably building against unstable or testing and running into https://git.hadrons.org/cgit/debian/pkgs/libaio.git/commit/debian/control?id=8d2d6c2930be1e34cb357ab4f1b8d42471a16f77 (time64 transition means `libaio1` package doesn't exist anymore).

**Comment by sienacompany** [comment]
I am running:

FROM debian:sid-slim

which was working nice for over than one year.

Yesterday I could workaround with:

# apt-get install -y libaio1
/usr/bin/curl -o libaio1_0.3.113-5_amd64.deb http://ftp.us.debian.org/debian/pool/main/liba/libaio/libaio1_0.3.113-5_amd64.deb
dpkg -i libaio1_0.3.113-5_amd64.deb


May I have to use a debian:bookworm-slim image from now to be able to install it via apt-get ?

**Comment by tianon** [comment]
I think maybe you've misunderstood -- I do not maintain `libaio` in Debian Unstable (which is also known as "Sid").  It has had a change with an ABI break, which means the package has a new name.  If you're installing it because you have some non-Debian binary you're copying into your container image, you will need to make appropriate adjustments that match your use case -- nobody else can make those for you.  If you want to continue using Unstable, you'll need to verify whether the ABI break affects your usage of the library, and if so, recompile your binary to compensate.  Honestly though, you're probably a lot better off using Stable (which is currently Bookworm).
