### ISSUE TITLE
unstable-slim image update needed

### ISSUE THREAD

**Issue by tkatila** [debuerreotype/docker-debian-artifacts#218]
Similar to https://github.com/debuerreotype/docker-debian-artifacts/issues/168, the `unstable-slim` base image's glibc is not the same as available from the unstable repository. Compiling a binary on the `unstable-slim` base and trying to run it on top of the `unstable-slim` results in:
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found
```

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/16766 :+1:
