### ISSUE TITLE
libgnutls30 symbol lookup error on Ubuntu 22.04

### ISSUE THREAD

**Issue by ascaron37** [debuerreotype/docker-debian-artifacts#224]
Host: Ubuntu 22.04.4
Docker: 27.0.3

I don't know if this is the right place to post the issue, because it seems to be some weird combination of my Ubuntu 22.04 host and the actual version of libgnutls30 on Debian. On an Ubuntu 20.04 host this works without problems. With the older image bookworm-20240612-slim it works on 22.04.4 as well. But maybe you have a hint for me on what to check/fix on the host.
When I try to update the container I receive the following error:
```
$ sudo docker run -ti --entrypoint=bash debian:bookworm-slim
root@2c92a67b2c98:/# apt-get update
/usr/lib/apt/methods/http: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: gnutls_pkcs7^get_crt_raw2, version GNUTLS_3_4
/usr/lib/apt/methods/http: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: gnutls_pkcs7^get_crt_raw2, version GNUTLS_3_4
/usr/lib/apt/methods/http: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: gnutls_pkcs7^get_crt_raw2, version GNUTLS_3_4
Reading package lists... Done
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (127)
E: Method /usr/lib/apt/methods/http did not start correctly
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (127)
E: Method /usr/lib/apt/methods/http did not start correctly
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (127)
E: Method /usr/lib/apt/methods/http did not start correctly
E: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease
E: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease
E: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by tianon** [comment]
I haven't seen this specific one before, but my top of head guess would be full disk or seccomp (see https://github.com/docker-library/official-images/issues/16829 and #122)

**Comment by ascaron37** [comment]
Thank you very much for the quick response. I am afraid it's neither. Have plenty of disk space left and seccomp was in version 2.5.3. On Ubuntu 20.04 it is 2.5.1 and it works. I installed version 2.5.4 (which bookworm uses) anyway, but it still does not work.

**Comment by ascaron37** [comment]
After updating to the newest image from 20240722 the issue was fixed.
I also tried with another Ubuntu 22.04 host and it did not have any issues with the 20240701 release. So no idea what the problem is with my specific host. But since it is fixed I close the issue.

Thank you very much for your help!
