### ISSUE TITLE
debian12 - fatal error in libgcrypt

### ISSUE THREAD

**Issue by mukundhan90** [debuerreotype/docker-debian-artifacts#226]
Hello, we are encountering an error when we perform 'apt-get update'. This issue is related to FIPS enabled node. Is there any workaround available to use on FIPS node?

fatal error in libgcrypt, file ../../src/misc.c, line 92, function _gcry_fatal_error: requested algo not in md context
 
Fatal error: requested algo not in md context
Aborted

**Comment by tianon** [comment]
Does Debian even have/honor "FIPS mode" ? 🤔

**Comment by tianon** [comment]
Aha, https://bugs.debian.org/1014517

**Comment by tianon** [comment]
To paraphrase, this is a known issue, and one that's probably not very likely to be fixed.  Sorry!
