### ISSUE TITLE
can't build for ppc64el

### ISSUE THREAD

**Issue by paleozogt** [debuerreotype/docker-debian-artifacts#227]
Trying to build with `ppc64el`:

```bash
$ ./docker-run.sh ./examples/debian.sh --arch=ppc64el output sid '2024-09-03 13:23:12'
...
chroot: failed to run command '/bin/true': No such file or directory
```

It looks like it works for other arches like `amd64`.  Any idea what's going wrong?

**Comment by tianon** [comment]
Can your system run ppc64le binaries?  (the `arch-test` package/command can help you answer this, if you don't already know)

**Comment by paleozogt** [comment]
Oops -- my qemu binfmts weren't setup properly.  Sorry!

**Comment by tianon** [comment]
Nice, glad we got it figured! :+1:
