### ISSUE TITLE
Missing architectures for `bullseye-slim`

### ISSUE THREAD

**Issue by Earlopain** [debuerreotype/docker-debian-artifacts#229]
20240904 has 7 archs: https://hub.docker.com/layers/library/debian/bullseye-20240904/images/sha256-2a1c9a0e7aa4fcad4d6319547bfcc0d8a7a290fada438d6fabc416f137cf12b4?context=explore
20240926 only has 4: https://hub.docker.com/layers/library/debian/bullseye-20240926/images/sha256-a9f115e23865353139b9312d7596b5183e5c76b4b96830a739304e06e1ed2588?context=explore

It's been 3 days so I would expect the rest to have popped up by now.

**Comment by fauust** [comment]
Hi!
Same here, this broke https://github.com/fauust/docker-systemd/actions/runs/11104559503/job/30853000512.

Is this on purpose to support less arch on Debian oldstable? I did not saw any Debian announce though.

**Comment by tianon** [comment]
It actually should've happened about a month ago, but I had a glitch that stopped it. 😅

See https://lists.debian.org/debian-announce/2024/msg00004.html

(Short version: yes, it's expected, it won't be reverted, see Debian LTS for details)

**Comment by Earlopain** [comment]
That's fair. Is this documented anywhere? I checked supported architectures at https://hub.docker.com/_/debian which still lists many. Autogenerated somewhere I assume. If a debian version goes LTS, the build matrix here is reduced?

**Comment by tianon** [comment]
It's officially documented at https://wiki.debian.org/LTS (I'm not aware of anywhere more official -- even the above linked announcement links to this page 😅).

If Debian isn't building for / supporting an architecture, yes, we match that (they'll probably be removed from the Debian archive/mirrors soon, so we don't really have much choice in the matter, but if it's unsupported, that makes sense).

**Comment by Earlopain** [comment]
Yeah, ok. I missed that page in the announcement. I'm a bit confused by that since it already only lists 4 architectures for bookworm as well (no `mips64le` for example) but that still has many architectures.

Anyways, not that important. I'll just drop those since it seems like at some point they will be gone for bookworm here as well. It seems better to only build for the minimum variants so that it works in the future as well.
