### ISSUE TITLE
how could i build debian:stretch-slim for mips64le

### ISSUE THREAD

**Issue by jcxian** [debuerreotype/docker-debian-artifacts#23]
I want to build debian:stretch-slim docker image for mips64le.But there is no rootfs.tar.xz for mips64le. how can I do for it?

**Comment by tianon** [comment]
See https://github.com/debuerreotype/debuerreotype, especially https://github.com/debuerreotype/debuerreotype/blob/9ec84f9c5b895107644d2666ad031f51ef6a34ba/Dockerfile#L3-L12:

```dockerfile
# bootstrapping a new architecture?
#   ./scripts/debuerreotype-init /tmp/docker-rootfs stretch now
#   ./scripts/debuerreotype-minimizing-config /tmp/docker-rootfs
#   ./scripts/debuerreotype-gen-sources-list /tmp/docker-rootfs stretch http://deb.debian.org/debian http://security.debian.org
#   ./scripts/debuerreotype-tar /tmp/docker-rootfs - | docker import - debian:stretch-slim
# alternate:
#   debootstrap --variant=minbase stretch /tmp/docker-rootfs
#   tar -cC /tmp/docker-rootfs . | docker import - debian:stretch-slim
# (or your own favorite set of "debootstrap" commands to create a base image for building this one FROM)
FROM debian:stretch-slim
```

**Comment by jcxian** [comment]
i want to build images for mips64el, but there is nothing for mips64el.

**Comment by jcxian** [comment]
FROM debian:stretch-slim is for amd64,there is no image for mips64el.

**Comment by tianon** [comment]
Yes, follow the directions I linked above to create a `debian:stretch-slim` analog for mips64el, then use that as the bootstrap to complete the full proper build.
