### ISSUE TITLE
/etc/passwd contains entries for list, irc, gnats

### ISSUE THREAD

**Issue by olberger** [debuerreotype/docker-debian-artifacts#26]
Hi.

Unless mandated by Debian policy, I fail to see the need for entries in /etc/passwd for users like lists, irc or gnats on any Docker container based on debian or debian-slim (tested for stable). Check with :
```$ docker run --rm -it debian:stable-slim cat /etc/passwd```

May not do much harm, but confusing at least

**Comment by tianon** [comment]
I'm not convinced this is the right place to file this -- we don't modify `/etc/passwd` at all, so whatever contents it has come directly from the assorted packages in the archive (which should be mostly `base-passwd`, if I'm not mistaken):

https://sources.debian.org/src/base-passwd/stretch/passwd.master/

```diff
$ diff -u <(docker run --rm debian:stretch-slim cat /etc/passwd) <(curl -fsSL 'https://sources.debian.org/data/main/b/base-passwd/3.5.43/passwd.master' | tr '*' 'x')
--- /dev/fd/63	2018-01-29 09:18:04.549222254 -0800
+++ /dev/fd/62	2018-01-29 09:18:04.549222254 -0800
@@ -16,4 +16,3 @@
 irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
 gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
 nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
-_apt:x:100:65534::/nonexistent:/bin/false
```

**Comment by olberger** [comment]
TBH, I'd kinda expected this... but preferred to ask. I think I know what to do next. Will try to keep this posted

**Comment by olberger** [comment]
I've had a quick look at the BTS, and it seems this is quite standard (UID < 100 being always there cause belonging to base-passwd). So I guess this is not a bug ;-)
