### ISSUE TITLE
Bash 4.4.18-1 fails to install on multiple foreign platforms

### ISSUE THREAD

**Issue by vicamo** [debuerreotype/docker-debian-artifacts#29]
```
Setting up bash (4.4.18-1) ...
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
dpkg: error processing package bash (--configure):
 installed bash package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 bash
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Affected arichitectures are:
* buster-mips
* buster-mips64el
* buster-mipsel
* buster-ppc64el
* sid-mips
* sid-mips64el
* sid-mipsel
* sid-powerpc
* sid-ppc64el

See Debian [bug 889869](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889869). Version [4.4.18-1.1](https://packages.debian.org/sid/bash) has been released on [Feb 13](http://snapshot.debian.org/archive/debian/20180213T153535Z/pool/main/b/bash/). CI [build error](https://travis-ci.org/vicamo/docker-brew-debian/builds/347551936) for my fork.

**Comment by yosifkit** [comment]
This is not really a bug in debuerrotype or the artifacts housed in this repo. The snapshot URL that has the updated version is [`20180213T153535Z`](http://snapshot.debian.org/archive/debian/20180213T153535Z/pool/main/b/bash/), while your build is using [`20180213T000000Z`](https://travis-ci.org/vicamo/docker-brew-debian/jobs/347551943#L1239), so it will not see the new packages.

**Comment by vicamo** [comment]
@yosifkit , from [the commit](https://github.com/debuerreotype/docker-debian-artifacts/blob/132a85df5e5e1528b46bcd44e8bfcc9d82ffce2d/buster/rootfs.debuerreotype-epoch) you have updated timestamp to __1518480000__:
```
$ LC_ALL=C TZ=UTC date --date=@1518480000
Tue Feb 13 00:00:00 UTC 2018
```
And the correct timestamp for __Tue Feb 13 15:35:35 UTC 2018__ should be:
```
$ LC_ALL=C TZ=UTC date --date="Tue Feb 13 15:35:35 UTC 2018" +%s
1518536135
```
So it's true my build was based on __20180213T000000Z__, because it fetches https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/buster/rootfs.debuerreotype-epoch for timestamp you're using.

**Comment by tianon** [comment]
I see that this is a bug, and likely a valid one, but what I don't understand is why it's being filed here?  `qemu-user-static` is known to interact poorly with quite a lot of software (Java and Go are especially bad, for example).  This repo doesn't support any of the listed architectures except `ppc64le`, which does work properly on real hardware.

**Comment by tianon** [comment]
(If the intent is to prompt an update to this repo's epoch, that should happen after this weekend: https://lists.debian.org/debian-stable-announce/2018/03/msg00000.html)
