### ISSUE TITLE
Images including build-essential

### ISSUE THREAD

**Issue by ChristophBerg** [debuerreotype/docker-debian-artifacts#3]
Hi,
would it be possible to add image flavors that include build-essential+debhelper?
Thanks!

**Comment by paultag** [comment]
Seems like a good idea to me! @tianon any thoughts on problems we might hit?

**Comment by tianon** [comment]
See the sbuild directories (on the relevant dist branches) for some experimental tarballs I've been playing with that work well as drop-in tarballs for sbuild/schroot. 👍

I'm not sure I'm sold on making them explicit Docket variants, though.  What's the benefit to users over providing their own two-line `Dockerfile`? (Especially since they're already likely to want more, such as whatever source it is they're looking to build.)

**Comment by julian-klode** [comment]
Since I currently have a working docker backend for sbuild, I am playing with that, and the overhead of installing build-depends with a local apt-cacher-ng can basically be ignored IMO.

**Comment by tianon** [comment]
Now that I'm at a computer, see https://github.com/debuerreotype/docker-debian-artifacts/tree/76c6cfebee0dede81763bd3ba0b3cdaa163d2bf3/stretch/sbuild for a more concrete example (which is an `armhf` tarball I've personally used drop-in with `sbuild` of `stretch` at 2017-06-20).  Using the `debuerreotype` tools, it should be reasonably trivial to build similar reproducible tarballs for our own uses if those don't suit you (or you prefer to build your own, which if you use the same serial/epoch, should be bit-for-bit identical :smiling_imp: :smile:).

https://github.com/debuerreotype/debuerreotype/blob/ce5cb9f5a0eb2aa171587339d50126139750a6d8/build.sh#L137-L140 represents most of the difference (ensuring `build-essential` and `fakeroot` are installed, same as `--variant=buildd` and `sbuild-createchroot`), but it also includes `deb-src` entries and `/dev` contents (which the standard Docker tarballs do not, given that most Docker users don't need `deb-src` and Docker itself provides `/dev`).

@julian-klode that sounds awesome! :smile:  I've played with that a bit myself (not directly in `sbuild`, but using Docker for doing builds on the fly), and do agree that having a cache makes most of the overhead pretty moot, and is one of the (many) reasons I'm always hesitant to add more variations that simply add more packages. :sweat_smile:

**Comment by tianon** [comment]
(Anyone curious about @julian-klode's Docker `sbuild` backend should check out https://bugs.debian.org/867176 :metal:)

**Comment by ChristophBerg** [comment]
@tianon: Our use case here is building some (one!) local package via .gitlab-ci.yml. The storage is dead slow (that should be fixed as well, yeah), and most of the build time is spent on installing packages on top of the base image. 
I don't want to provide my own docker file because I'd need it only once, and I don't actually want to start developing docker stuff (I'm interested in that local package only). As "build Debian packages" seems to be an obvious use case for the base image, I'd think base+build-essential should be part of the "debian/" image namespace. (Yes I could grab random other images from the hub, but I'd like something official. If it's not coming directly from *.debian.org, it should still be debian/something.)

**Comment by tianon** [comment]
Ah, something under `debian/` seems appropriate! :metal:

@paultag thoughts on something like `debian/sbuild:jessie`, etc built from those tarballs I'm already generating?  Is there a name you think might be more appropriate?  I'm currently generating `sbuild/rootfs.tar.xz` file for every suite/codename, and it wouldn't be much more work to create a basic `Dockerfile` too and get those pushed up somewhere useful.

**Comment by paultag** [comment]
Yeah super for it if that makes it easier! Maybe call it buildd or build-essential? Maybe pbuild wants to get on Docker support :)

**Comment by tianon** [comment]
Calling it `buildd` would match the debootstrap variant name it's explicitly emulating (which only differs from minbase in that it includes `build-essential`), so that sounds great to me! :+1:

I'll see if I can work up some simple automation for pushing some useful bits to `debian/buildd`.

**Comment by tianon** [comment]
https://hub.docker.com/r/debian/buildd/tags/ :+1: 

(not automated yet, but it's a good start)

**Comment by tianon** [comment]
Scripts are up now in https://github.com/debuerreotype/docker-debian-buildd-scripts -- just need to hook them up to a periodic Jenkins job and I think we're good!

**Comment by tianon** [comment]
Ok, I've finally hooked this up to an automated Jenkins job, so we should be all good here. :+1:
