### ISSUE TITLE
Package build-essentials can not be installed for jessie if security updates are removed

### ISSUE THREAD

**Issue by bb-dsa** [debuerreotype/docker-debian-artifacts#34]
Trying to setup a Docker container fails as build-essential cannot be installed because of the following error:
```
build-essential : Depends: gcc (>= 4:4.9.1) but it is not going to be installed
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
```
The Dockerfile is defined as follows:
```
FROM 	library/debian:jessie
RUN cp /etc/apt/sources.list	/tmp/sources.list	&& \
	grep -v security /tmp/sources.list 	>/etc/apt/sources.list
RUN	apt-get	update
RUN	apt-get	install	-y build-essential
```
It seems that the base jessie image has changed recently and does not reflect the original version. The problem seems to be that libc has been updated to version 8u10 .

Removing security updates was an attempt to be able to install the PowerPC cross compiler from emdebian.org. As we are using the container for cross compilation, security updates are not a must have.

**Comment by tianon** [comment]
Have you seen https://toolchains.bootlin.com/?  It might be a simpler and more up-to-date option than trying to work with emdebian.org (which has gone through various degrees of being supported over time).

**Comment by bb-dsa** [comment]
This may work as a mid-term solution which would require thorough testing. Is there a SHA reference to the old image that could be used temporarily? If so, how long would this reference be valid?

**Comment by tianon** [comment]
You could try using the date-suffixed tags:

- `debian:jessie-20180312`
- `debian:jessie-20180213`
- `debian:jessie-20171210`

If those are insufficient, you can get even stronger repeatability guarantees from an explicit digest SHA, which you can get historical values for from https://github.com/docker-library/repo-info/blob/master/repos/debian/remote/jessie.md.  That page lists the current digests (`docker pull debian:jessie@sha256:xxxxx`), but you can go back through the commit history of that file to see previous values.
