### ISSUE TITLE
Consider replacing 'inetutils-ping' with 'iputils-ping'

### ISSUE THREAD

**Issue by mato** [debuerreotype/docker-debian-artifacts#36]
I recently spent some time tracking down surprising failures in CI scripts relying on `ping -f`, where these scripts would always time out when run inside a `debian:stretch` container, but succeed on a Debian stretch host (and, in this case, other host OSes such as *BSD).

A minimal test case to reproduce the issue is to compare the behaviour of `time ping -fq -c 1000 127.0.0.1` inside a container with that directly on the host. In the container case, the command takes 10 seconds to complete, whereas on the host it completes almost instantly.

The root cause of the issue are the different versions of `ping` installed _by default_ on a Debian system (`iputils-ping`) vs. that installed in the official Docker image (`inetutils-ping`), and their differing interpretations of how "flood ping" is supposed to behave.

Please consider replacing `inetutils-ping` in the official Docker image with `iputils-ping` for consistency with how a normal Debian system would behave. Also, in my experience, the "well-known" behaviour of flood ping (e.g. on the BSDs) is consistent with that of `iputils-ping`, which I believe is derived from the BSD code.

**Comment by tianon** [comment]
Originally, we chose `inetutils-ping` because it was smaller.  Since then, we've introduced the `-slim` variants which explicitly do not include `ping` at all, making the size point fairly moot.  I'm +1 on making the change. :+1:

(For reference, we don't get `ping` by default because we use `debootstrap --variant=minbase`.  When using the standard variant, `iputils-ping` is included which is why a "standard" install of Debian includes it.)

**Comment by tianon** [comment]
Updated in https://github.com/debuerreotype/debuerreotype/commit/dc4b7a412bac05d12dcbc3c370f39bcc226fa29c.

**Comment by yosifkit** [comment]
> Outputs packets as fast as they come back or one hundred times per second, whichever is more.

From what I can tell, inetutils-ping, is getting higher average round trips and so is limiting itself to 100 per second.

```console
$ # inetutils
root@f6592dfc4615:/# time ping -f -c 1000 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
--- 127.0.0.1 ping statistics ---
1000 packets transmitted, 1000 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.008/0.047/0.138/0.000 ms

real	0m10.099s
user	0m0.011s
sys	0m0.051s
$# iputils
root@c6c3cd7a6b6d:/# time ping -fq -c 1000 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
 
--- 127.0.0.1 ping statistics ---
1000 packets transmitted, 1000 received, 0% packet loss, time 29ms
rtt min/avg/max/mdev = 0.004/0.009/0.053/0.005 ms, ipg/ewma 0.029/0.006 ms

real	0m0.033s
user	0m0.002s
sys	0m0.031s
```

But it seems if I set the wait time instead of flood, (`-i 0`) both will send as fast as possible with no cap:

```console
$# inetutils
root@f6592dfc4615:/# time ping -qi 0 -c 1000 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
--- 127.0.0.1 ping statistics ---
1000 packets transmitted, 1000 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.004/0.006/0.026/0.000 ms

real	0m0.007s
user	0m0.004s
sys	0m0.003s
$# iputils
root@c6c3cd7a6b6d:/# time ping -qi 0 -c 1000 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.

--- 127.0.0.1 ping statistics ---
1000 packets transmitted, 1000 received, 0% packet loss, time 4ms
rtt min/avg/max/mdev = 0.001/0.002/0.033/0.002 ms, ipg/ewma 0.004/0.001 ms

real	0m0.007s
user	0m0.002s
sys	0m0.005s
```

**Comment by tianon** [comment]
Pushed up https://github.com/docker-library/oi-janky-groovy/commit/75fcf0154d876c6a380d8bf3f651467bb1776419, and now have triggered rebuilds.

This is going to replace/supplement https://github.com/docker-library/official-images/pull/4281.

**Comment by tianon** [comment]
(Closing, since all the changes are in place and now we're simply waiting for builds. :+1:)

**Comment by TimWolla** [comment]
FWIW: This change broke one of my perl images, because `netbase` now is missing from `debian:stretch`. `netbase` was a dependency of `inetutils-ping`, but is not a dependency of `iputils-ping`.

`perl` only depends with a `Recommends` on `netbase` and the software required `/etc/protocols` to be present [1]. I have no idea who’s at fault for not properly specifying the dependencies here, but netbase probably is present on almost all production Debian systems anyway.

I solved the issue by explicitely installing `netbase` in my image.

[1]
```
Apr 28 23:11:19 xxx systemd[1]: Started MtpolicyD.
Apr 28 23:11:28 xxx docker[4607]: 2018/04/28-23:11:28 Mail::MtPolicyd (type Net::Server::PreFork) starting! pid(7)
Apr 28 23:11:28 xxx docker[4607]: Use of uninitialized value in subroutine entry at /usr/share/perl5/Net/Server/Proto.pm line 125.
Apr 28 23:11:28 xxx docker[4607]: Binding to TCP port 12345 on host :: with IPv6
Apr 28 23:11:28 xxx docker[4607]: 2018/04/28-23:11:28 Can't connect to TCP port 12345 on :: [No such file or directory]\n  at line 68 in file /usr/share/perl5/Net/Server/Proto/TCP.pm
Apr 28 23:11:28 xxx docker[4607]: 2018/04/28-23:11:28 Server closing!
Apr 28 23:11:28 xxx systemd[1]: Stopping MtpolicyD...
```

**Comment by mato** [comment]
On Saturday, 28.04.2018 at 16:37, Tim Düsterhus wrote:
> FWIW: This change broke one of my perl images, because `netbase` now is missing from `debian:stretch`. `netbase` was a dependency of `inetutils-ping`, but is not a dependency of `iputils-ping`.

Ah yes, I did notice that after manually installing `iputils-ping` in an
image before this change, `netbase` started showing up as a candidate for
auto-removal. On a normal system it's probably installed explicity.

@tianon: You'll want to add `netbase` to the list of packages to be
installed otherwise `/etc/{network,protocols,rpc,services}` will be
missing.
