### ISSUE TITLE
_proto

### ISSUE THREAD

**Issue by rizplate** [debuerreotype/docker-debian-artifacts#37]

**Comment by yosifkit** [comment]
Issue has no description. Closing.

**Comment by sentience** [comment]
@rizplate Are you able to comment on what prompted you to open this?

We’ve just started experiencing a connection issue in our Docker containers that seems suspiciously related:

> Error: The following HTTP request failed.
<https://github.com/NoRedInk/elm-decode-pipeline/zipball/3.0.0/>
> 
> FailedConnectionException2 "github.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)

If there were a recently-introduced issue in the Debian Jessie Docker images, it would certainly explain the behaviour we’re seeing!

**Comment by tianon** [comment]
Likely https://github.com/debuerreotype/docker-debian-artifacts/issues/36#issuecomment-385212707

**Comment by rizplate** [comment]
yes it seems netbase package was not there in recent debian docker changes done few days ago.
i.e. our debian dockers stoped building as base image was broken.
we fixed it by apt-get install netbase in Dockerfile. HTH
