### ISSUE TITLE
please add minimal editor

### ISSUE THREAD

**Issue by vvchik** [debuerreotype/docker-debian-artifacts#38]
Currently, default Image has no any editor.
It would be great to have one minimal POSIX compatible like vi or vim-tiny.

CentOs and Alpine have vi installed by default.
Ubuntu haven't 
But now even vipw command doesn't work.

**Comment by yosifkit** [comment]
Short answer: no, Debian and Ubuntu images are kept minimal on purpose.

Longer reasoning:
It is not possible to remove anything in an image `FROM` it, but it is easily added in your own Dockerfile:

```Dockerfile
FROM debian:stretch
RUN apt-get update && apt-get install -y vim-tiny && rm -rf /var/lib/apt/lists/*
```

Specifically for Ubuntu images:
> We consume upstream's tarballs directly from https://partner-images.canonical.com/core/ (per their explicit request) -- Canonical decides what they contain, and they track issues/requests over at https://bugs.launchpad.net/cloud-images. :+1:
>
> \- https://github.com/tianon/docker-brew-ubuntu-core/issues/82#issuecomment-293735895
