### ISSUE TITLE
add apt-utils

### ISSUE THREAD

**Issue by lifeofguenter** [debuerreotype/docker-debian-artifacts#39]
see: https://github.com/phusion/baseimage-docker/issues/319

**Comment by yosifkit** [comment]
> > Is there any harm (barring the warning) caused by not having this package installed?
>
> No, it has not yet stopped anything from running. Just a warning, and nothing else.
>
> \- https://github.com/tianon/docker-brew-ubuntu-core/issues/59#issuecomment-241154499

Since this is just a warning, there is no need for us to install an extra package that users cannot remove later.
