### ISSUE TITLE
debian:jessie: /bin/ping has no suid or cap_net_raw capability

### ISSUE THREAD

**Issue by xlq** [debuerreotype/docker-debian-artifacts#40]
`/bin/ping` is included in the Debian Jessie image, but is neither SUID nor has the cap_net_raw capability (so non-root users in the container cannot ping). This has changed in the last month, since ce40fb3adcc6 had the SUID bit set on /bin/ping.

Removing and re-installing the inetutils-ping package adds the capability, so the package is supposed to have set it.

Steps to reproduce:
1. `docker pull debian:jessie`
2. `docker run -it --rm debian:jessie ls -l /bin/ping` shows the SUID bit is not set
3. `docker run -it --rm debian:jessie getcap /bin/ping` shows no capabilities

**Comment by tianon** [comment]
Doh, we used to include `inetutils-ping` which uses setuid, but now we include `iputils-ping` which appears to prefer capabilities, but our tar creation process doesn't preserve those.  I've opened https://github.com/debuerreotype/debuerreotype/pull/38 to try to fix this oversight in the tooling. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/4497 :+1:
