### ISSUE TITLE
Missing folders in /usr/share/man for stable-slim

### ISSUE THREAD

**Issue by thrawn-sh** [debuerreotype/docker-debian-artifacts#42]
Starting the container with:
`$> docker run -it debian:stable-slim`

Installing software inside the container:
`$> apt update && DEBIAN_FRONTEND=noninteractive apt-get --yes install openjdk-8-jre-headless`

leads to the following error:
```update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-8-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Errors were encountered while processing:
 openjdk-8-jre-headless:amd64
```

Removing all files and folders in `/usr/share/man` seems to break at least some packages, maybe only delete the files and retain the folders?

**Comment by tianon** [comment]
See also https://github.com/debuerreotype/docker-debian-artifacts/issues/24 and thus https://github.com/debuerreotype/debuerreotype/issues/10.
