### ISSUE TITLE
Where is dpkg-architecture?

### ISSUE THREAD

**Issue by pslacerda** [debuerreotype/docker-debian-artifacts#43]
I couldn't compile Pillow because the link `libz.so` -> `libz.so.1` is missing in `/lib/x86_64-linux-gnu`. The [Debian Policy Manual](https://www.debian.org/doc/debian-policy/#document-ch-sharedlibs) says that `.so` link should be installed along with the development packages. The `zlib1g-dev` package was installed but `libz.so` is missing.

```console
root@eba34fc4c7ff:/# dpkg-query -l | grep zlib
ii  zlib1g:amd64            1:1.2.8.dfsg-5        amd64        compression library - runtime
ii  zlib1g-dev:amd64        1:1.2.8.dfsg-5        amd64        compression library - development
root@eba34fc4c7ff:/# ls /lib/x86_64-linux-gnu/libz*
/lib/x86_64-linux-gnu/libz.so.1  /lib/x86_64-linux-gnu/libz.so.1.2.8
```

For details see https://github.com/docker-library/python/issues/305.

**Comment by pslacerda** [comment]
The real question: was removing `dpkg-dev` and `dpkg-architecture` intentional?  It was there, but now it isn't.

**Comment by yosifkit** [comment]
This is not an issue in the Debian image. To my knowledge it has never included `dpkg-dev`. See my comment in related python issue.
