### ISSUE TITLE
dockerhub pull failing when --disable-content-trust=false

### ISSUE THREAD

**Issue by westonandrosadamson** [debuerreotype/docker-debian-artifacts#49]
This started a few hours ago:

`$ docker pull --disable-content-trust=false debian:jessie
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
ERRO[0000] Metadata for timestamp expired               
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
ERRO[0000] Metadata for timestamp expired               
Error: remote repository docker.io/library/debian out-of-date: timestamp expired at Wed Oct 3 15:40:21 UTC 2018`

Note that things work without the `--disable-content-trust=false`

`$ docker pull debian:jessie
jessie: Pulling from library/debian
Digest: sha256:53ad4744268d3ae3ab11efffe55693e8f1f0d5cb93742fd1d2f26f0a4a84f839
Status: Image is up to date for debian:jessie`

From the error messages it's not clear if the problem is downloading the new metadata (and the cache is expired), or if the metadata from dockerhub has somehow expired.

**Comment by westonandrosadamson** [comment]
I confirmed this is not just a problem with jessie:

`$ docker pull --disable-content-trust=false debian:stretch
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
ERRO[0000] Metadata for timestamp expired               
WARN[0000] Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely 
ERRO[0000] Metadata for timestamp expired               
Error: remote repository docker.io/library/debian out-of-date: timestamp expired at Wed Oct 3 15:40:21 UTC 2018`

**Comment by tianon** [comment]
Looks like Docker's having some issues with their public notary service -- not sure why they don't show up on https://status.docker.com/, but I think all images are affected.

There's really nothing we can do about it; I'd suggest contacting Docker, sorry!

**Comment by westonandrosadamson** [comment]
Oh, thanks! I sure wish the error messages were easier to understand!
