### ISSUE TITLE
Error when I run exec kill

### ISSUE THREAD

**Issue by BraisGabin** [debuerreotype/docker-debian-artifacts#5]
Using the image `debian:8` I can run `docker exec container kill 1` and it works fine.

But with the new image: `debian:9` I get this error:

> `rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"kill\": executable file not found in $PATH"`

Am I doing something wrong? Is this a bug or just a desired BC?

My workaround right now is: `docker exec container bash -c "kill 1"`.

**Comment by tianon** [comment]
That'd be because "kill" is a bash builtin, and "/bin/kill" is provided by
the "procps" package (which was only included in jessie's minbase set by
accident as a dependency of something else); see https://packages.debian.
org/stretch/procps. :+1:

Why use "docker exec container kill" instead of just "docker kill --signal
XXX container" ? (for XXX, you probably want TERM or INT)

**Comment by BraisGabin** [comment]
> Why use "docker exec container kill" instead of just "docker kill --signal XXX container"?

There's not any good reason. I just use it because it worked and I didn't know about the `--signal` argument.

> which was only included in jessie's minbase set by accident

So it's the desired behaviour. We can close this issue then. Thanks! :)

**Comment by Clopma** [comment]
> That'd be because "kill" is a bash builtin, and "/bin/kill" is provided by the "procps" package (which was only included in jessie's minbase set by accident as a dependency of something else); see https://packages.debian. org/stretch/procps. 👍 Why use "docker exec container kill" instead of just "docker kill --signal XXX container" ? (for XXX, you probably want TERM or INT)

But this other command doesn't specify a PID, what if I don't want to kill the container? In the first exampleit is trying to kill the PID 1

**Comment by tianon** [comment]
Then I'd suggest doing something like `bash -c 'kill XXX'` instead (or invoking `kill` from the host on the container PID you want, which can be seen in `docker top`).
