### ISSUE TITLE
debian:*sid images have broken openssl implementation?

### ISSUE THREAD

**Issue by kojiromike** [debuerreotype/docker-debian-artifacts#50]
Even with ca-certificates installed (to contrast with #15), the ssl behavior of sid has strange problems. Case in point:

```
FROM debian:sid-slim
RUN apt-get -qqy update && apt-get -qqy install curl
RUN curl -v https://packagecloud.io
```

does

```
Step 1/3 : FROM debian:sid-slim
 ---> 15a24e403848
Step 2/3 : RUN apt-get -qqy update && apt-get -qqy install curl
 ---> Running in 23ed5635d96e
<SNIP>
Setting up curl (7.61.0-1) ...
Processing triggers for libc-bin (2.27-6) ...
Processing triggers for ca-certificates (20180409) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 23ed5635d96e
 ---> 9c6ffae6de03
Step 3/3 : RUN curl -v https://packagecloud.io
 ---> Running in c61b3301774b
* Rebuilt URL to: https://packagecloud.io/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 50.97.198.58...
* TCP_NODELAY set
* Connected to packagecloud.io (50.97.198.58) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* (304) (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* (304) (IN), TLS handshake, Server hello (2):
{ [93 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5416 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (OUT), TLS alert, Server hello (2):
} [2 bytes data]
* error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
The command '/bin/sh -c curl -v https://packagecloud.io' returned a non-zero code: 35
```

This site has a perfectly valid TLS 1.2 cert from most systems. I ran a [qualys ssl labs](https://www.ssllabs.com/ssltest/analyze.html?d=packagecloud.io) report on it and it came back clean. The ssl behavior appears correct on images built on base images _other_ than `debian:*slim`

**Comment by tianon** [comment]
Seems to be a bug in Debian Unstable / Sid -- if I swap `debian:sid-slim` for `debian:stretch-slim`, it works fine.

**Comment by kojiromike** [comment]
Confirmed -- I used the wrong slice -- it's sid, not slim, that's the problem.

**Comment by tianon** [comment]
Unfortunately, this appears to be an issue in Debian -- likely either in `src:openssl` or `src:curl`.  There's nothing specific to the Docker image which should be causing this.  If more investigation occurs and it turns out there's something we need to fix or change in the image (and not something to fix in Debian itself), I'm happy to reconsider.

**Comment by jpawlowski** [comment]
I would like to re-open this as I was noticing a similar issue but only on ARM32v5/v7 based images.
I was not able to reproduce that with either x86_64, i386 or AMD64v8.

@tianon do you still think this is a Debian issue or could it be something platform specific?

How I tested for every platform:

- Install Docker Desktop on macOS (which comes with qemu natively)
- `docker run -it <platform>/debian:buster /bin/bash`
- `apt update && apt install -y curl wget npm`

After the preparation, the following 2 tests were performed:
1. `curl -fsSL https://registry.npmjs.org` --> fails on ARM32, all other platforms are ok
2. `wget -qO- https://registry.npmjs.org` --> surprisingly it works on _all_ platforms, also ARM32
3. `npm install -g npm` --> fails on ARM32, all other platforms are ok

Same result appears in my Travis QEMU builds that are based on Debian Buster for ARM32.

Given that this only appears on ARM32, I didn't want to open a Debian bug report unless to be sure that it is not an issue with the Docker images. Could anybody help me to check into this?

**Comment by DeeDeeG** [comment]
I'm seeing something seemingly related to this in Buster now.

Does anyone here know of a good way to bring this up with upstream Debian folks?

(Specifically, my issue is that running `phantomjs --version` breaks under Buster, and the workaround is to set an environment variable `OPENSSL_CONF=/etc/ssl/`. The image I am hoping to use (and have been seeing this issue on) is `ruby:2.5.7-slim`, which is based on Buster slim.)

**Comment by remi-debette** [comment]
Hi everyone, 
Same issue on the python 3.7.5 image, based on Debian buster.
I have to do the `OPENSSL_CONF=/etc/ssl/` workaround to get a `curl https//......` to work.
