### ISSUE TITLE
Jessie image incredibly slow when run unprivileged on Stretch

### ISSUE THREAD

**Issue by mjameswh** [debuerreotype/docker-debian-artifacts#53]
Here is a strange situation observed on our server: some processes (including `apt-get update`) run _very_ slowly when run in a jessie container on a stretch container.

For example:

```
time docker run -it --rm debian:jessie apt-get update
[...]
*real    0m57.226s*
*user    0m0.080s*
*sys    0m0.024s*
```
vs
```
time docker run -it --rm --privileged debian:jessie apt-get update
[...]
real	0m11.330s
user	0m0.072s
sys	0m0.024s
```
vs
```
time docker run -it --rm debian:stretch apt-get update
[....]
*real    0m3.575s*
*user    0m0.084s*
*sys    0m0.020s*
```

All are running from the same machine. Exact times varies a little from run to run, but the ratios between each cases remains relatively stable. I haven't tried on a different stretch host. I have however tried the same tests on my Mac (I think the linux VM used internally is Alpine based, right?), and I get no significant difference between the `--privileged` and the non-privileged `jessie` cases.

The difference between the stretch case and the privileged jessie case could arguably be attributed to the fact that their might be more/closer mirrors for stretch than for the older jessie distribution, or maybe that `apt-get` itself is now more efficient... But the fact that it gets 6 times slower simply because it is run unprivileged definitely smells fishy.

I also observe what appears to be the same pattern with a php based application (we are still doing some tests to confirm, but up to this point, it indeed appears to be the very same pattern).

**Comment by mjameswh** [comment]
Forgot to mention...

```
docker images | egrep "jessie|stretch"
debian                                          stretch             be2868bebaba        3 weeks ago         101MB
debian                                          jessie              efdec82af25a        3 weeks ago         127MB

docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

uname -a
Linux myserver 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
```

**Comment by tianon** [comment]
I think this is a case of https://bugs.launchpad.net/bugs/1332440 (https://bugs.debian.org/896790, for example).

In other words, this is a known issue by the APT maintainers that they're unwilling to fix in Jessie due to Jessie being (now) unsupported.

The workaround would be to use `--ulimit` on your containers, ala:

```console
$ time docker run --rm debian:jessie-slim apt-get update -qq

real	0m33.937s
user	0m0.107s
sys	0m0.010s

$ time docker run --rm --ulimit nofile=1024:1024 debian:jessie-slim apt-get update -qq

real	0m2.337s
user	0m0.040s
sys	0m0.016s
```

**Comment by mjameswh** [comment]
Indeed, that fixes it. Thanks a lot. Too bad I failed to find that issue before posting here ;)
