### ISSUE TITLE
ca-certificates failing to install for experimental/slim

### ISSUE THREAD

**Issue by nthh** [debuerreotype/docker-debian-artifacts#61]
`Updating certificates in /etc/ssl/certs...
mv: cannot move '/tmp/ca-certificates.crt.tmp.oxIEgX' to a subdirectory of itself, 'ca-certificates.crt'
dpkg: error processing package ca-certificates (--configure):`

Seems to be some issue with the latest sid/experimental releases? I used an older tag of sid and had no issues.

**Comment by tianon** [comment]
If this works fine in the non-slim variant, it's likely https://github.com/debuerreotype/debuerreotype/issues/10.

If it also fails in the non-slim variant, https://bugs.debian.org/src:ca-certificates would be the appropriate place to look for an upstream issue.
