### ISSUE TITLE
slim variants for *-backports

### ISSUE THREAD

**Issue by fboudra** [debuerreotype/docker-debian-artifacts#63]
Would it be possible to generate slim variants for the -backports distributions? or would you rather use for example debian:stretch-slim as a base images and then include the backports repositories in the images that we'd like to produce?

`debian    stretch-slim            b805107aed7b        2 weeks ago         55.3MB`
`debian    stretch-backports   95460cd18b99        2 weeks ago         101MB`
`debian    stretch                    0af60a5c6dd0         2 weeks ago         101MB`

**Comment by tianon** [comment]
I think looking at the `Dockerfile` for the `-backports` variants is probably a good exercise here:

https://github.com/debuerreotype/docker-debian-artifacts/blob/3e751c2c2f60037e9231ed94bbd1f95347af2c87/stretch/backports/Dockerfile

I've found for most places I need this, it's indeed more effective for me to simply add that `RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list` one-liner (or something similar to it) to my own `Dockerfile`, which also makes it easier to keep it as part of the block it's being added for so it can be reverted on a Debian update more clearly/cleanly.

It's provided as a tag primarily for folks looking to consume the Debian images as more "standard" environments, and not something we have plans to extend support for.
