### ISSUE TITLE
debian:stretch-slim: cannot install postgresql-client

### ISSUE THREAD

**Issue by fboudra** [debuerreotype/docker-debian-artifacts#64]
On debian stretch, postgresql-client package install manpages. It's causing package install failure on debian:stretch-slim image:
```
Setting up postgresql-client-9.6 (9.6.11-0+deb9u1) ...
update-alternatives: using /usr/share/postgresql/9.6/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man7/ABORT.7.gz.dpkg-tmp': No such file or directory
dpkg: error processing package postgresql-client-9.6 (--configure):
 subprocess installed post-installation script returned error exit status 2
```

A simple workaround in my images is to create the directories:
`mkdir -p /usr/share/man/man1 /usr/share/man/man7`

I'm not sure what's the appropriate place to report this issue. I feel it could make sense to create the directories in the base -slim images for such packages and avoid everybody to work around in their images...

**Comment by tianon** [comment]
See #42, #24, and thus https://github.com/debuerreotype/debuerreotype/issues/10.

**Comment by fboudra** [comment]
worth a FAQ entry at this point :)
