### ISSUE TITLE
sources list in wheezy should be switched to archive

### ISSUE THREAD

**Issue by JamesCohen-awin** [debuerreotype/docker-debian-artifacts#65]
In the last 24 hours `apt-get update` has started failing due to the package repos being moved to archive.debian.org

To exhibit the error behaviour
```
$ docker run --rm -it debian:wheezy apt-get update
Get:1 http://security.debian.org wheezy/updates Release.gpg [1601 B]
Ign http://deb.debian.org wheezy Release.gpg
Get:2 http://security.debian.org wheezy/updates Release [52.3 kB]
Ign http://deb.debian.org wheezy-updates Release.gpg
Ign http://deb.debian.org wheezy Release
Get:3 http://security.debian.org wheezy/updates/main amd64 Packages [743 kB]
Ign http://deb.debian.org wheezy-updates Release
Err http://deb.debian.org wheezy/main amd64 Packages
  404  Not Found
Err http://deb.debian.org wheezy-updates/main amd64 Packages
  404  Not Found
Fetched 797 kB in 1s (403 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://deb.debian.org/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

To fix `/etc/apt/sources.list` should be corrected to:
```
deb http://archive.debian.org/debian wheezy main
deb http://security.debian.org/debian-security wheezy/updates main
```

**Comment by tianon** [comment]
Yep, this is expected -- Wheezy has been EOL since April 25th, 2016 (which is when the security team stopped supporting it and the LTS team picked it up, but the LTS support even ended 31 May 2018).

The next update to the `debian` image should be removing the `wheezy` tags from the supported list altogether.  If you check out `debian:squeeze`, you'll see that it was treated similarly post-EOL.

At some point (hopefully soon), we'll get `wheezy` added to `debian/eol` (https://hub.docker.com/r/debian/eol).

**Comment by JamesCohen-awin** [comment]
Understood. We'll fix this downstream then.

**Comment by TheMeier** [comment]
Same problem with jessie. Will this also be not changed?

**Comment by tobiasoort** [comment]
Indeed same with Jessie. See https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by tobiasoort** [comment]
I recorded the jessie issue in its own issue: #66

**Comment by tianon** [comment]
See https://github.com/debuerreotype/docker-debian-artifacts/issues/66#issuecomment-476648047 -- this should be resolved with this next update (although I'm not 100% sure what it's going to do to `debian:wheezy` given that http://security.debian.org/debian-security/dists/wheezy/updates/ exists and https://deb.debian.org/debian/dists/wheezy/ does not, but I _think_ this will remove `debian:wheezy` appropriately given the current code).

**Comment by mphilipps** [comment]
>  but I think this will remove debian:wheezy appropriately given the current code). 

As in move it to debian/eol?

For now I am working around that with 
```
# wheezy is no longer provided by deb.debian.org, replaced with archive.debian.org
RUN sed -i 's|^deb http://deb.debian.org/debian|deb http://archive.debian.org/debian/|' /etc/apt/sources.list
# remove wheezy-updates (no longer exist, as there are no planned point releases)
RUN sed -i '/wheezy-updates/d' /etc/apt/sources.list
```
in my top-level Dockerfile.

**Comment by boussou** [comment]
Even after having switched to archive, I can't build any of our wheezy based Dockerfiles.
We have legacy software that relies on this exact version.
The source.list is: 
`deb http://archive.debian.org/debian wheezy main contrib  non-free`

Now, any package I try to install, ends up with "it is not going to be installed".
Of course; I tried to update, upgrade, dist-upgrade, fix broken. No Luck.

Example with apache2:
```
The following packages have unmet dependencies:
 apache2 : Depends: apache2-mpm-worker (= 2.2.22-13+deb7u6) but it is not going to be installed or
                    apache2-mpm-prefork (= 2.2.22-13+deb7u6) but it is not going to be installed or
                    apache2-mpm-event (= 2.2.22-13+deb7u6) but it is not going to be installed or
                    apache2-mpm-itk (= 2.2.22-13+deb7u6) but it is not going to be installed
           Depends: apache2.2-common (= 2.2.22-13+deb7u6) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

If wheezy is abandonned, can you tell us how to do (even if required to setup our own server) to be able build our dockerfiles? 
Thanks

**Comment by sjackman** [comment]
I'm not sure if it's the same issue that I had, but make sure that you have both `archive` and `security` in your `sources.list`. See https://github.com/Homebrew/homebrew-portable-ruby/blob/91a6b054267519d6c2c71fa84f0a89e6f7f5175c/docker/Dockerfile.x86_64#L10

**Comment by boussou** [comment]
Good idea, but there is nothing here: 
[http://security-cdn.debian.org/debian-security/dists/](http://security-cdn.debian.org/debian-security/dists/)

If you browse it, you can see there is no wheezy folder.

**Comment by sjackman** [comment]
That's curious. There definitely was 18 days ago on March 28 when I merged that commit. I take it that it's changed since then? I definitely did not work before without the security repo in `sources.list`, and I saw an error similar to what you're seeing now.

**Comment by tianon** [comment]
Ok, in the interest of finally stopping the perfect from being the enemy of the good, I've pushed up `debian/eol:wheezy` (https://hub.docker.com/r/debian/eol).

Hopefully sometime Soon™ I'll re-push it via some official Debuerreotype process along with all the other existing tags so that they're reproducible too (see also https://github.com/debuerreotype/debuerreotype/pull/58, https://github.com/debuerreotype/debuerreotype/pull/59, https://github.com/debuerreotype/debuerreotype/pull/60, https://github.com/debuerreotype/debuerreotype/pull/61), but for now this should be enough.

As with all `debian/eol` images, it's appropriately targeting http://archive.debian.org and should have enough settings baked in for `apt-get update` and `apt-get install` invocations to succeed out-of-the-box.

This finally concludes this issue. :balloon:

**Comment by sjackman** [comment]
Thank you, Tianon!

**Comment by boussou** [comment]
Thanks.

I can confiirm,, it works, just by replacing the 1st line to --> "FROM debian/eol:wheezy".

**Comment by tianon** [comment]
For anybody who was excited by the idea of the EOL images being properly reproducible and multi-arch, see https://twitter.com/tianon/status/1121243343436963840?s=19

**Comment by boussou** [comment]
Great ! Thanks a lot.
I will try it today.
We all have legacy software ;-)
