### ISSUE TITLE
TLS host verification fails on ARM32 with Debian Buster images

### ISSUE THREAD

**Issue by jpawlowski** [debuerreotype/docker-debian-artifacts#68]
I would like to refer back to issue #50 as I was noticing a similar issue but only on ARM32v5/v7 based images.
I was not able to reproduce that with either x86_64, i386 or ARM64v8.

@tianon do you still think this is a Debian issue or could it be something platform specific?

How I tested for every platform:

- Install Docker Desktop on macOS (which comes with qemu natively)
- `docker run -it <platform>/debian:buster /bin/bash`
- `apt update && apt install -y curl wget npm`

After the preparation, the following 2 tests were performed:
1. `curl -fsSL https://registry.npmjs.org` --> fails on ARM32, all other platforms are ok
2. `wget -qO- https://registry.npmjs.org` --> surprisingly it works on _all_ platforms, also ARM32
3. `npm install -g npm` --> fails on ARM32, all other platforms are ok

Same result appears in my Travis QEMU builds that are based on Debian Buster for ARM32.
Note that all this working fine on Debian 9 Stretch images on _all_ platforms including ARM32.

Given that this only appears on ARM32, I didn't want to open a Debian bug report unless being sure that it is not an issue with the Docker images. Could anybody help me to check into this?

**Comment by tianon** [comment]
QEMU is not a great substitute for real hardware -- for example, both OpenJDK and Go binaries are known to have serious issues running.

I tried your example on some real ARM hardware and it appears to work fine there:

```console
$ docker pull arm32v7/debian:buster
buster: Pulling from arm32v7/debian
Digest: sha256:ea2f5d38f6c8efc86e6a82f31725b16fe18c6c45f049cd0fa3c90cb4f647c8ca
Status: Image is up to date for arm32v7/debian:buster

$ docker run -it --rm arm32v7/debian:buster

root@f43833e0152a:/# apt update -qq
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@f43833e0152a:/# apt install -yqq curl wget npm
...
done.

root@f43833e0152a:/# curl -fsSL https://registry.npmjs.org > curl.txt; echo $?
0

root@f43833e0152a:/# wget -qO- https://registry.npmjs.org > wget.xt; echo $?
0

root@f43833e0152a:/# diff -u curl.txt wget.txt; echo $?
--- curl.txt	2019-04-29 17:05:59.158195259 +0000
+++ wget.txt	2019-04-29 17:06:07.906235873 +0000
@@ -1 +1 @@
-{"db_name":"registry","doc_count":1234513,"doc_del_count":341,"update_seq":1422751,"purge_seq":0,"compact_running":false,"disk_size":23851397255,"data_size":14284019613,"instance_start_time":"1556549459732087","disk_format_version":6,"committed_update_seq":1422751}
\ No newline at end of file
+{"db_name":"registry","doc_count":1234513,"doc_del_count":341,"update_seq":1423014,"purge_seq":0,"compact_running":false,"disk_size":23909244373,"data_size":14283998344,"instance_start_time":"1556512536370507","disk_format_version":6,"committed_update_seq":1423006}
\ No newline at end of file
1

root@f43833e0152a:/# npm install -g npm
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
added 426 packages from 800 contributors in 9.023s
root@f43833e0152a:/# echo $?
0
```

**Comment by jpawlowski** [comment]
Thanks for testing this yourself!
Hm, the thing is, it is working perfectly fine with Stretch on both my Mac, my Intel NUC and Travis CI. None of them would work with Buster. On Travis CI, I am able to quickly change the QEMU binary so I went for both QEMU 4.0 and 3.1.0-3 but the result is the same: Stretch works fine, Buster doesn't.

Any other idea? Do you this needs to be investigated by the package maintainers?

**Comment by tianon** [comment]
Yep, either that or the QEMU maintainers.
