### ISSUE TITLE
Why does uname -a mention ubuntu?

### ISSUE THREAD

**Issue by TZubiri** [debuerreotype/docker-debian-artifacts#71]
https://superuser.com/questions/1435938/why-docker-debian-image-show-ubuntu-as-os

uname -a on debian:stretch-slim returns: 
Linux d7264ece7327 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux

**Comment by yosifkit** [comment]
From the answer on the linked stackexchange question (https://superuser.com/a/1437232):

> Docker containers use the kernel of their host, and your host is running an Ubuntu kernel.

For example on my host that is gentoo:
```console
$ uname -a
Linux isengard 4.19.32-gentoo #1 SMP Fri Mar 29 14:56:47 PDT 2019 x86_64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz GenuineIntel GNU/Linux
$ docker run -it --rm debian
root@7bf154272d7f:/# uname -a
Linux 7bf154272d7f 4.19.32-gentoo #1 SMP Fri Mar 29 14:56:47 PDT 2019 x86_64 GNU/Linux
root@7bf154272d7f:/# 
```
