### ISSUE TITLE
debian:buster-slim 3x larger than stable-slim

### ISSUE THREAD

**Issue by anarcat** [debuerreotype/docker-debian-artifacts#73]
Hi!

From what I can tell, `stable-slim` is 22MB, which is nice and small. But `buster-slim`, for some reason, has hit 69M already.. Is there any reason for this discrepancy? Is buster really that bigger? `sid-slim` is 27MB, so it really seems like a problem specific to buster...

**Comment by yosifkit** [comment]
If you are looking at the numbers on Docker Hub tags list, `22Mb` is the *transport* size of `debian:stretch-slim`, while it really is ` ~ 55.28 Mb` on disk ([repo-info](https://github.com/docker-library/repo-info/blob/098b2a608ec03a52eced984a1098ed4fc0a75d0b/repos/debian/local/stretch-slim.md)). `debian:buster-slim` is similar in size: `27Mb` on Hub listing and ` ~ 69.20 Mb` on disk ([repo-info](https://github.com/docker-library/repo-info/blob/098b2a608ec03a52eced984a1098ed4fc0a75d0b/repos/debian/local/buster-slim.md)).

`debian:sid-slim` is very close to buster with `27Mb` and `~ 69.31 Mb`

**Comment by anarcat** [comment]
i see, i was indeed looking at transport vs storage sizes. sid and buster do seem 10MB larger however:

```
debian                  stable-slim         87f6f3b892c0        2 weeks ago         55.3MB
debian                  sid-slim            e46a3b919e05        2 weeks ago         69.3MB
debian                  buster-slim         fb802176ee50        2 weeks ago         69.2MB
```

probably not a deal breaker, but it would be nice to trim that down...

thanks!
