### ISSUE TITLE
docker hub "testing" still pulls buster

### ISSUE THREAD

**Issue by ldelossa** [debuerreotype/docker-debian-artifacts#77]
currently pulling down "debian:testing" tag and cat'ing os-release shows buster
```
❯ docker run -it --rm debian:testing /bin/bash
root@4e84d0532740:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@4e84d0532740:/#
```

Current Debian documentation says "bullseye" is current testing.

**Comment by tianon** [comment]
Right, this is a quirk of how Debian updates that file and is entirely expected for `/etc/os-release` -- the change to `bullseye` in that file needs to be uploaded to Debian Unstable, and then migrate to Testing, and *then* we need an image update to pull in that change.

If you check `/etc/apt/sources.list`, it will have the correct appropriate values.

See also https://github.com/debuerreotype/docker-debian-artifacts/issues/75.

**Comment by ldelossa** [comment]
@tianon 

```
root@4e84d0532740:/# cat /etc/apt/sources.list
# deb http://snapshot.debian.org/archive/debian/20190708T033000Z testing main
deb http://deb.debian.org/debian testing main
```

can I infer the release from this information ? I'm trying to programmatically interpret which Debian container I'm running at a specific time statically (so without running a command)

**Comment by tianon** [comment]
Yep -- https://deb.debian.org/debian/dists/testing/InRelease includes:

```
Suite: testing
Codename: bullseye
```

**Comment by ldelossa** [comment]
thanks!
