### ISSUE TITLE
Could you include deb-src entry in the sources.list by default

### ISSUE THREAD

**Issue by agustinhenze** [debuerreotype/docker-debian-artifacts#78]
Hi, we are using these images in salsa-ci https://salsa.debian.org/salsa-ci-team/pipeline happily :). We were wondering if it's possible to have the deb-src entry in the sources.list by default.

**Comment by tianon** [comment]
As alluded to in https://github.com/debuerreotype/docker-debian-artifacts/issues/3#issuecomment-312886032, we exclude `deb-src` lines intentionally given that the vast majority of image users do not require them (and they would thus result in additional unnecessary load on the mirrors but more importantly wasted bandwidth/time for users).

When I need `deb-src` lines, I typically use something like `RUN find /etc/apt/sources.list* -type f -exec sed -i 'p; s/^deb /deb-src /' '{}' +` (which should work equally well in Ubuntu-based images as it does in Debian-based images, and will work for many third-party repositories too).

**Comment by agustinhenze** [comment]
Actually we did something similar https://salsa.debian.org/salsa-ci-team/pipeline/blob/master/images/dockerfiles/gbp#L14. OK, makes sense, thanks for the explanation! :blush:
