### ISSUE TITLE
What happened to "free" command in stretch?

### ISSUE THREAD

**Issue by jamshid** [debuerreotype/docker-debian-artifacts#80]
It makes it hard to upgrade images when they drop commonly used commands. What happened to free? 
```
$ docker run -ti debian:jessie bash
root@f65a39b1c7c8:/# which free
/usr/bin/free

$ docker run -ti debian:stretch bash
root@e3cb345b3d62:/# which free
root@e3cb345b3d62:/# :-(
```
PS: I know free doesn't make much sense in a container since it's not limited to the container but I use it with `--privileged` to check free memory on the docker server.

**Comment by tianon** [comment]
The `free` command is part of the `procps` package, which isn't part of the "essential" set and thus isn't part of our images.

See also https://github.com/tianon/docker-brew-debian/issues/13, https://github.com/tianon/docker-brew-debian/issues/14, and https://github.com/debuerreotype/docker-debian-artifacts/issues/5 for some previous discussions of this same package.

> PS: I know free doesn't make much sense in a container since it's not limited to the container but I use it with `--privileged` to check free memory on the docker server.

Not at all -- the available memory reported by `free` will always be the value of the host (no `--privileged` necessary) unless you're in an LXD container with [lxcfs](https://linuxcontainers.org/lxcfs/introduction/) providing `/proc/meminfo` appropriately.

As for alternatives, I'd suggest reading `/proc/meminfo` directly or using something that includes `busybox` (such as `alpine` or the `busybox` image itself) which includes an implementation of the `free` command (and will likely be a much smaller image).
