### ISSUE TITLE
Running Debian image fails (with invalid opcode error) while Ubuntu succeeds

### ISSUE THREAD

**Issue by drasch** [debuerreotype/docker-debian-artifacts#81]
Here's an example from the `stable-slim` and `buster-slim` images.

`[1670227.726250] traps: bash[58470] trap invalid opcode ip:7f16596e4190 sp:7ffece635be8 error:0 in libc-2.28.so[7f16595b0000+148000]`

Running the `ubuntu` base image does not generate any such error on this AWS instance.

For reference, here are the CPU flags on this machine:
```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xb000037
cpu MHz         : 2699.804
cache size      : 46080 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
bogomips        : 4600.11
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by drasch** [comment]
Thanks for the quick response!

Seems to happen with the `rootfs.tar.gz` bootstrap that's the source of the Docker iamges, also happens with a fresh `debootstrap`; so it's clearly an issue upstream somewhere, but I'm not sure if I should go all the way to Debian libc-2.28 or somewhere else? Advice?

**Comment by tianon** [comment]
Given you're running on RHEL 7, I imagine the kernel of that could be a potential culprit here -- have you tried a newer kernel or different distribution on the same instance type?

**Comment by drasch** [comment]
Closing until I've got more information. I've been unable to reproduce on a CentOS 7.6 install using the same config. I need to isolate whether it's an AWS issue or otherwise.
