### ISSUE TITLE
Illegal instruction, core dumped on unix commands

### ISSUE THREAD

**Issue by precbioinf** [debuerreotype/docker-debian-artifacts#86]
I am trying to run debian/buster-slim on RHEL 7.6 using docker 19.03.6/
```
> docker run -it debian/buster-slim bash
root@6e238fb8d8c2:/# ls
Illegal instruction (core dumped)
root@6e238fb8d8c2:/# exit
```
Only bash intrinsics and ldd works. All other commands in /bin and elsewhere core dumps.
Trying with regular buster also same problem:
```
> docker run -it debian/buster bash
root@084f8d070e47:/# ls
Illegal instruction (core dumped)
root@084f8d070e47:/# exit
```
However, trying with stretch-slim works:
```
docker run -it debian:stretch-slim bash
root@5f1d5bd159fa:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@5f1d5bd159fa:/#
```
Any idea why this is happening ?

Is this related to https://github.com/debuerreotype/docker-debian-artifacts/issues/81 ?

Thanks

**Comment by tianon** [comment]
I mean, it's definitely not out of the question -- which architecture are you running on?  I *think* this would have to be something weird with the kernel or the CPU mismatching with what Debian supports for your architecture, but it's hard to say for sure.

**Comment by stappersg** [comment]
@precbioinf please provide additional information.    Quoting the 2020-02-22 response:
> which architecture are you running on?

Thing I would like to know if you are, same as #81, on AWS?

**Comment by precbioinf** [comment]
i am on red Hat enterprise 7.6.

Thanks
Peter Li

**Comment by stappersg** [comment]
> > Thing I would like to know if you are, same as #81, on AWS?

> i am on red Hat enterprise 7.6.

At that is hosted at AWS? [yes/no]

**Comment by saisujithkp** [comment]
@stappersg I'm part of the same team as Peter, This issue still persists in the servers we are using. The servers are not hosted on AWS.

**Comment by saisujithkp** [comment]
The servers are running the Debian Stretch images perfectly fine, but the issue is occurring only with Buster, @stappersg can you think of a reason as to why that is the case?

**Comment by precbioinf** [comment]
Just a bit more background, the physical hosts are running vmware, the instances are running rhel 7.6.
We found there were discrepancy between the physical cpu model/version vs the virtual cpu model/version (from /proc/cpuinfo).
However, Debian buster failures are not associated with the differences, i.e. on some cpu model/version pairs, the container runs fine, but on another machine the same cpu model/version pair, it won't.

**Comment by precbioinf** [comment]
Here is a bit more on the images that failed to run.

> docker -it debian:buster cat /etc/passwd
Illegal instruction (core dumped)

I captured the core dump, copied to another container on a host that was able to run debian:buster.
Brought up gdb and got this:

```
root@baef3858bd8a:/tmp# gdb /bin/cat core.22039
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
...
Reading symbols from /bin/cat...(no debugging symbols found)...done.
[New LWP 7]
Core was generated by `cat /etc/passwd'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f80cd4a1190 in __strncasecmp_l_sse42 ()
    at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:929
929     ../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
```
Which seems to be related to cpu architecture detection and dynamic library loading for the specific cpu optimizations.
But given that same cpu model/version seems to work for some debian:buster, but not for others makes me wonder if the problem is something else.

Thanks,
Peter

**Comment by saisujithkp** [comment]
We were able to finally find the issue, A program called CyLance was running on our servers. We were able to determine cylance was causing the issue by monitoring its logs while using the debian containers. Cylance had a module where it was scans kernal packages and it seems to blacklist debian kernal packages. @precbioinf  will be closing the issue soon.

**Comment by precbioinf** [comment]
We might open another issue related to cylance black-listing debian image files. But this one will close.

**Comment by stappersg** [comment]
To others that never have hear about cylance before https://en.wikipedia.org/wiki/Cylance
