### ISSUE TITLE
GPG error with debian:jessie

### ISSUE THREAD

**Issue by prawen** [debuerreotype/docker-debian-artifacts#93]
Hello,

I'm using debian:jessie as my docker base image and getting below error while doing apt-get update.
`"W: GPG error: http://archive.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1587841717"`

I was suggested to manually fetch an uptodate debian-archive-keyring package and manually install it. I have done the same by downloading it from `http://ftp.cn.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2019.1_all.deb`

But now I'm getting below error 
`W: GPG error: http://archive.debian.org jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553`

Please help!

**Comment by prawen** [comment]
I think it's because I was adding below lines before apt-get update
`RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list`

**Comment by tianon** [comment]
This sounds like your copy of `debian:jessie` is out of date, and you probably need to either `docker pull debian:jessie` or use the `--pull` argument of `docker build`.

**Comment by tianon** [comment]
Oh, and I just noticed you're using `archive.debian.org`, which is a frozen repository for EOL releases, so that's probably also related to your issues.
