### ISSUE TITLE
buster image exits prematurely

### ISSUE THREAD

**Issue by Mossman1215** [debuerreotype/docker-debian-artifacts#94]
Hi Team,
I'm confused because when I try to run docker and docker-compose with debian:buster or debian:latest images I'm getting return code 132.
for instance when i run this command it exits immediately

`sudo docker run -it debian:buster /bin/bash
`
Running for stretch gives me a terminal as expected
```
tcantwell@DaMossman:~$ sudo docker run -it debian:stretch /bin/bash
root@405d2d361c3c:/# 

```
Has anyone else experienced this or do i have some bad cached data?

Cheers,
Moss

**Comment by tianon** [comment]
Hmm, I'm not able to reproduce: :confused:

```console
$ docker pull debian:buster
buster: Pulling from library/debian
Digest: sha256:4ab3309ba955211d1db92f405be609942b595a720de789286376f030502ffd6f
Status: Downloaded newer image for debian:buster
docker.io/library/debian:buster

$ docker run -it --rm debian:buster bash
root@9273f9ef80f9:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Mossman1215** [comment]
Found it !
i'm forced to use an old ass kernel for a security app to work (cylance)
so it's my 4.15 kernel that is not working
works fine on hwe kernel on ubuntu 18.04
5.3.0-53-generic
