### ISSUE TITLE
debian:stretch-slim not available for linux/s390x 

### ISSUE THREAD

**Issue by ajgrande924** [debuerreotype/docker-debian-artifacts#98]
can the stretch-slim tag be built for linux/s390x? need this for zlinux support: https://hub.docker.com/_/debian?tab=tags&page=1&name=stretch-slim

**Comment by tianon** [comment]
Unfortunately not -- Debian Stretch is no longer supported on `s390x`.  See https://github.com/docker-library/official-images/pull/8405 and https://wiki.debian.org/LTS upstream for more details.

**Comment by tianon** [comment]
To expound on that slightly, as far as the Debian Security and Release teams are concerned, Debian Stretch is now officially EOL.  The Debian LTS team is now maintaining *select* updates for Debian Stretch, and only for the architectures noted in https://wiki.debian.org/LTS.

If you need a temporary workaround, `s390x/debian:stretch-slim` should still exist and work for some amount of time (until/unless the mirrors are already updated to remove `s390x`).
